"use client";
import {useEffect,useRef} from "react";
import * as THREE from "three";
import {OrbitControls} from "three/examples/jsm/controls/OrbitControls.js";
import {walls,rooms} from "./floorplan";
type V3=[number,number,number];
export default function HouseScene({section=false,active="overview",cutaway=false,time=12}:{section?:boolean;active?:string;cutaway?:boolean;time?:number}){
 const host=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!host.current)return;const el=host.current,scene=new THREE.Scene();scene.background=new THREE.Color(0xf2f0eb);
 const focus:Record<string,V3>={overview:[0,0,0],courtyard:[-.72,0,-1.37],living:[1.52,0,2.55],dining:[1.52,0,6.1],primary:[-2.25,0,2.82],guest:[-.88,0,-5.14]};const target=focus[active]||focus.overview;
 const selected=active!=="overview"?rooms[active]:undefined;const roomSize=selected?Math.max(selected.w,selected.d):16;
 const cam=new THREE.OrthographicCamera(-8,8,8,-8,.1,100);cam.position.set(section?10:11,section?12:15,section?15:18);cam.lookAt(...target);cam.zoom=active==="overview"?.77:Math.min(2.2,10/roomSize);cam.updateProjectionMatrix();
 const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;el.appendChild(renderer.domElement);
 const wallMat=new THREE.MeshStandardMaterial({color:0xf4f1eb,roughness:.88,transparent:cutaway,opacity:cutaway?.48:1});const floorMat=new THREE.MeshStandardMaterial({color:0xd9d6cf,roughness:1});const courtMat=new THREE.MeshStandardMaterial({color:0xc7c3ba,roughness:1});
 const addBox=(x:number,y:number,z:number,w:number,h:number,d:number,mat:THREE.Material,edge=false)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;scene.add(mesh);if(edge){const lines=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),new THREE.LineBasicMaterial({color:0x77736d,transparent:true,opacity:.35}));lines.position.copy(mesh.position);scene.add(lines)}return mesh};
 const clipWall=(a:{x:number;z:number;w:number;d:number},b:{x:number;z:number;w:number;d:number},pad=.24)=>{const x1=Math.max(a.x-a.w/2,b.x-b.w/2-pad),x2=Math.min(a.x+a.w/2,b.x+b.w/2+pad),z1=Math.max(a.z-a.d/2,b.z-b.d/2-pad),z2=Math.min(a.z+a.d/2,b.z+b.d/2+pad);return x2>x1&&z2>z1?{x:(x1+x2)/2,z:(z1+z2)/2,w:x2-x1,d:z2-z1}:null};
 if(!selected){addBox(0,-.13,0,9,.26,16,floorMat,true);Object.entries(rooms).forEach(([name,p])=>{if(name==="corridor")return;addBox(p.x,.015,p.z,p.w,.03,p.d,name.toLowerCase().includes("court")||name==="courtyard"?courtMat:floorMat)})}else addBox(selected.x,-.08,selected.z,selected.w,.16,selected.d,active==="courtyard"?courtMat:floorMat,true);
 walls.map(w=>selected?clipWall(w,selected):w).filter((w):w is {x:number;z:number;w:number;d:number}=>Boolean(w)).forEach(w=>addBox(w.x,.85,w.z,w.w,1.7,w.d,wallMat,true));
 // 平面图中五个主要门洞，以开启的门扇标明交通关系
 [[3.08,4.15,.78,0],[3.08,.05,.78,0],[3.08,-3.45,.78,0],[4.47,-3.05,.78,Math.PI/2],[2.15,-7.96,.78,Math.PI/2]].filter(([x,z])=>!selected||(Math.abs(x-selected.x)<=selected.w/2+.5&&Math.abs(z-selected.z)<=selected.d/2+.5)).forEach(([x,z,w,r])=>{const g=new THREE.Group();const leaf=addBox(0,.72,0,w,1.42,.045,wallMat,true);scene.remove(leaf);g.add(leaf);g.position.set(x,0,z);g.rotation.y=r+.72;scene.add(g)});
 const furnitureMat=new THREE.MeshStandardMaterial({color:0xe7e3dc,roughness:.82});const softMat=new THREE.MeshStandardMaterial({color:0xf7f5f0,roughness:1});const show=(id:string)=>active==="overview"||active===id;
 const bed=(x:number,z:number,rot=0)=>{const g=new THREE.Group();const part=(px:number,py:number,pz:number,w:number,h:number,d:number,m=furnitureMat)=>{const q=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);q.position.set(px,py,pz);q.castShadow=q.receiveShadow=true;g.add(q)};part(0,.18,0,1.65,.28,2.05);part(0,.39,.05,1.52,.24,1.82,softMat);part(-.4,.58,-.62,.62,.16,.43,softMat);part(.4,.58,-.62,.62,.16,.43,softMat);part(0,.72,-1,1.72,1.05,.12);g.position.set(x,0,z);g.rotation.y=rot;scene.add(g)};
 const stool=(x:number,z:number)=>{addBox(x,.23,z,.42,.46,.42,furnitureMat,true);addBox(x,.5,z+.16,.42,.48,.08,furnitureMat,true)};
 if(show("primary")){bed(-2.55,2.8);addBox(-3.65,.28,2.1,.48,.56,.48,furnitureMat,true);addBox(-1.45,.28,2.1,.48,.56,.48,furnitureMat,true);addBox(-4.02,.75,3.15,.48,1.5,2.45,furnitureMat,true);stool(-1.15,3.55)}
 if(show("guest")){bed(-.85,-5.35,Math.PI/2);addBox(-1.75,.28,-4.45,.48,.56,.48,furnitureMat,true);addBox(-1.85,.72,-6.35,.55,1.44,1.25,furnitureMat,true);stool(.45,-4.25)}
 if(show("living")){addBox(1.05,.32,2.7,.82,.5,2.15,softMat,true);addBox(.72,.65,2.7,.16,.58,2.15,softMat,true);addBox(1.82,.23,2.55,1.05,.24,.68,furnitureMat,true);addBox(2.82,.48,2.55,.18,.96,2.25,furnitureMat,true);stool(2.18,3.35)}
 if(show("dining")){addBox(1.55,.4,5.95,1.75,.12,.9,furnitureMat,true);[[.55,5.95],[2.55,5.95],[1.05,5.2],[2.05,5.2],[1.05,6.7],[2.05,6.7]].forEach(([x,z])=>stool(x,z));addBox(2.72,.52,7.15,.5,1.04,1.95,furnitureMat,true);addBox(1.65,.52,7.72,1.65,1.04,.48,furnitureMat,true)}
 if(show("courtyard")){[[-2.15,-.75,1.0],[1.15,-1.85,.75]].forEach(([x,z,s])=>{addBox(x,.55*s,z,.20*s,1.1*s,.20*s,furnitureMat,true);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(.68*s,1),furnitureMat);crown.position.set(x,1.45*s,z);crown.castShadow=true;scene.add(crown)});addBox(.15,.18,-2.85,1.5,.36,.55,furnitureMat,true);addBox(2.25,.22,-.35,.7,.44,.55,furnitureMat,true)}
 const daylight=Math.sin(((time-6)/12)*Math.PI);const warm=time<9||time>16;scene.add(new THREE.HemisphereLight(warm?0xffe3c5:0xffffff,0x77736d,.65+daylight*1.05));const angle=((time-6)/12)*Math.PI;const sun=new THREE.DirectionalLight(warm?0xffc58f:0xfff7e8,.45+daylight*3.15);sun.position.set(Math.cos(angle)*13,3+daylight*13,Math.sin(angle)*10-3);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-12;sun.shadow.camera.right=12;sun.shadow.camera.top=12;sun.shadow.camera.bottom=-12;scene.add(sun);
 const controls=new OrbitControls(cam,renderer.domElement);controls.target.set(...target);controls.enableDamping=true;controls.maxPolarAngle=1.52;controls.minZoom=.5;controls.maxZoom=2.5;
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);const k=w/h;cam.left=-8*k;cam.right=8*k;cam.top=8;cam.bottom=-8;cam.updateProjectionMatrix()};resize();const ro=new ResizeObserver(resize);ro.observe(el);let frame=0;const loop=()=>{controls.update();renderer.render(scene,cam);frame=requestAnimationFrame(loop)};loop();return()=>{cancelAnimationFrame(frame);ro.disconnect();controls.dispose();renderer.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose()});el.removeChild(renderer.domElement)}} ,[section,active,cutaway,time]);
 return <div ref={host} style={{width:"100%",height:"100%"}}/>;
}
