'use client';
import {useEffect,useRef,useState} from 'react';
import {Send,Terminal,ChevronDown,LoaderCircle} from 'lucide-react';
import {executePlan,validatePlan,shortcut,type CommandPort,type Command} from './commands';
type Entry={input:string;message:string;ok:boolean;source:string;plan?:string};
export function CommandPanel({port,ready}:{port:()=>CommandPort|null;ready:boolean}){
 const [input,setInput]=useState(''),[history,setHistory]=useState<Entry[]>([]),[open,setOpen]=useState(true),[busy,setBusy]=useState(false),[configured,setConfigured]=useState(false),[checked,setChecked]=useState(false);
 const request=useRef<AbortController|null>(null),active=useRef(true);
 useEffect(()=>{active.current=true;const c=new AbortController();void fetch('/factory/api/command',{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{configured:boolean}>;}).then(v=>{if(active.current){setConfigured(v.configured===true);setChecked(true);}}).catch(()=>{if(active.current)setChecked(true);});return()=>{active.current=false;c.abort();request.current?.abort();};},[]);
 async function submit(text:string,quick=false){if(!ready||!text.trim()||request.current)return;const p=port();if(!p)return;const c=new AbortController();request.current=c;setBusy(true);setInput('');let result;let plan:Command[]|null=null;let source='快捷指令';
 try{let direct:Command[]|null=null;try{direct=shortcut(text,p.context().devices);}catch(e){if(quick||!configured)throw e;}if(direct||quick||!configured){plan=direct;result=plan?executePlan(plan,p):{ok:false,message:'大模型尚未连接。请使用下方快捷指令，或输入“聚焦 RB-02”“跟随 AGV-03”。'};}
 else {source='DeepSeek';const timer=setTimeout(()=>c.abort(),30000);try{const response=await fetch('/factory/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,state:p.context().task}),signal:c.signal});const body=await response.json() as {error?:string;actions:unknown;clarification?:string};if(!response.ok)throw Error(body.error??'模型服务不可用。');if(c.signal.aborted||!active.current)return;if(!Array.isArray(body.actions))throw Error('模型返回格式无效。');if(body.actions.length){plan=validatePlan(body.actions,p.context().devices);result=executePlan(plan,p);}else result={ok:false,message:typeof body.clarification==='string'?body.clarification:'请补充具体的操作目标。'};}finally{clearTimeout(timer);}}
 }catch(e){result={ok:false,message:c.signal.aborted?'请求已取消或超时，未执行任何动作。':(e as Error).message};}
 finally{request.current=null;if(active.current)setBusy(false);}
 if(active.current&&result)setHistory(h=>[{input:text,...result,source,plan:plan?.map(c=>({start:'开始工单',pause:'暂停工单',resume:'继续工单',reset:'复位',status:'查询进度',overview:'全景',focus:'聚焦',follow:'跟随',ride:'车载视角'}[c.action])+(c.deviceId?' '+c.deviceId:'')).join(' → ')},...h].slice(0,12));
 }
 return <section className="command-panel" aria-label="车间指挥台"><button className="command-heading" onClick={()=>setOpen(!open)} aria-expanded={open}><span><Terminal size={18}/>车间指挥台</span><ChevronDown size={16} style={{transform:open?'':'rotate(-90deg)'}}/></button>{open&&<><p className="command-mode"><i/>{configured?'DeepSeek · 自然语言':'快捷指令模式'}<span>{!checked?'检查连接…':configured?'理解 → 执行':'大模型待连接'}</span></p><form onSubmit={e=>{e.preventDefault();void submit(input);}}><label className="sr-only" htmlFor="workshop-command">车间指令</label><input id="workshop-command" maxLength={500} value={input} onChange={e=>setInput(e.target.value)} placeholder={configured?'让三号车开工，镜头跟着它':'例如：聚焦 RB-02'} disabled={!ready||busy||!checked}/><button type="submit" disabled={!ready||busy||!input.trim()||!checked} aria-label="发送指令">{busy?<LoaderCircle size={17} className="command-spinner"/>:<Send size={17}/>}</button></form><div className="command-shortcuts">{['开始作业并跟车','暂停作业','继续作业','查看进度','回到全景'].map(s=><button key={s} disabled={!ready||busy} onClick={()=>void submit(s,true)}>{s}</button>)}</div>{busy&&<div className="command-pending" role="status">正在理解指令…<button onClick={()=>request.current?.abort()}>取消</button></div>}<div className="command-history" role="log" aria-live="polite">{history.length?history.map((h,i)=><div className={'command-entry '+(h.ok?'ok':'error')} key={i}><p className="command-input">{h.input}</p><p className="command-source">{h.source}{h.plan?' / '+h.plan:''}</p><p><span>{h.ok?'已执行':'未执行'}</span>{h.message}</p></div>):<p className="command-empty">{configured?'试试：靠近二号机械臂，或告诉我工单做到哪一步了。':'发送指令后，这里会显示实际执行结果。'}</p>}</div></>}</section>;
}

