'use client';
import { useEffect, useRef, useState } from 'react';
import { Box, Scan, Footprints, RotateCcw, Maximize2, Focus, ChevronRight, ArrowUpRight, Layers3, MousePointer2, Navigation } from 'lucide-react';
import { CommandPanel } from './command-panel';
import { TITLES, type TaskSnapshot } from './production-task';
import type { Workshop, Device } from './workshop';
export default function Home(){
 const host=useRef<HTMLDivElement>(null), engine=useRef<Workshop|null>(null);
 const [task,setTask]=useState<TaskSnapshot|null>(null);
 const [devices,setDevices]=useState<Device[]>([]),[selected,setSelected]=useState<Device|null>(null),[mode,setMode]=useState('overview'),[status,setStatus]=useState('正在构建你的车间视野…'),[ready,setReady]=useState(false),[locked,setLocked]=useState(false);
 useEffect(()=>{let cancelled=false; import('./workshop').then(async({Workshop})=>{if(cancelled||!host.current)return;try{const w=new Workshop(host.current,{select:setSelected,mode:setMode,lock:setLocked,task:setTask});engine.current=w;const items=await w.ready;if(cancelled)return;setDevices(items);setReady(true);setStatus('拖动旋转视角，点击设备靠近观察');}catch{setStatus('三维场景加载失败，请刷新重试或使用支持 WebGL 的浏览器。');}});return()=>{cancelled=true;engine.current?.dispose();};},[]);
 const focus=(d:Device)=>{engine.current?.focus(d.id);setStatus('正在观察 '+d.title);};
 return <main className="app-shell"><header className="topbar"><a className="brand" href="/factory/"><span className="brand-icon"><Box size={23}/></span><span>白境<span className="brand-light"> / 车间</span><small>WHITE WORKSHOP</small></span></a><div className="project-id">空间实验 01 <span>36 × 24 m · 扩展车间</span></div><button className="icon-button" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>setStatus('当前窗口不支持全屏，可在浏览器中打开。'));}}><Maximize2 size={17}/>全屏</button></header>
 <section className="stage"><div className="scene" ref={host} aria-label="可旋转和进入的三维生产车间"/>
 <div className="scene-heading"><div className="eyebrow"><i/> PRODUCTION STUDIO</div><h1>走进生产现场<span>。</span></h1><p>从全局，到每一个工位。</p></div>
 <nav className="view-switch" aria-label="视角模式"><button disabled={!ready} className={mode==='overview'?'active':''} onClick={()=>{engine.current?.overview();setStatus('拖动旋转 · 滚轮缩放 · 右键平移');}}><Layers3 size={17}/>车间总览</button><button disabled={!ready} className={mode==='walk'?'active':''} onClick={()=>{engine.current?.walk();setStatus('WASD 行走 · 鼠标转头 · Esc 释放鼠标');}}><Footprints size={17}/>进入车间</button></nav>
 <div className="control-rail"><section className="task-panel" aria-label="生产工单"><div className="task-head"><span className="eyebrow">W-001 / 装配工单</span><span className={'task-state '+task?.status}>{({idle:'待执行',running:'运行中',paused:'已暂停',done:'已完成'} as Record<string,string>)[task?.status??'idle']}</span></div><h2>{task?.title??'准备作业环境'}</h2><p className="task-route">缓存 02 → 装配线 02 → 成品缓存 01</p><div className="task-track"><i style={{width:(task?.progress??0)+'%'}}/></div><div className="task-meta"><span>{task?.elapsed??0} 秒</span><span>{task?.progress??0}%</span></div><div className="task-buttons"><button disabled={!ready} className="task-primary" onClick={()=>{const action=task?.status==='running'?'pause':task?.status==='paused'?'resume':'start';engine.current?.controlTask(action);}}>{task?.status==='running'?'暂停作业':task?.status==='paused'?'继续作业':task?.status==='done'?'再运行一轮':'开始作业'}</button><button disabled={!ready||task?.status==='idle'} onClick={()=>engine.current?.controlTask('reset')}>重置</button><button disabled={!ready} onClick={()=>{engine.current?.followVehicle();setStatus('跟随 03 号搬运车 · 拖动视角可退出跟随');}}>跟车</button></div><details><summary>作业步骤与物料状态</summary><ol>{TITLES.map((title,i)=><li key={title} className={task?.status==='done'||i<(task?.stage??0)?'complete':i===task?.stage&&task?.status!=='idle'?'current':''}><span>{String(i+1).padStart(2,'0')}</span>{title}</li>)}</ol><p>物料 W-001：{task?.processed?'已装配':'待装配'}<br/>当前位置：{task?.location??'原料缓存位'}</p></details></section><CommandPanel ready={ready} port={()=>engine.current}/></div>
 <aside className="equipment-panel"><div className="panel-top"><div><small>WORKSHOP DIRECTORY</small><h2>设备索引</h2></div><span>{devices.length.toString().padStart(2,'0')}</span></div><div className="device-list">{devices.map(d=><button disabled={!ready} key={d.id} className={selected?.id===d.id?'selected':''} onMouseEnter={()=>engine.current?.hoverDevice(d.id)} onMouseLeave={()=>engine.current?.hoverDevice(null)} onClick={()=>focus(d)}><span className={'device-mark '+d.kind}>{d.kind==='agv'?<Navigation size={18}/>:d.kind==='robot'?<Focus size={18}/>:<Box size={18}/>}</span><span><strong>{d.title}</strong><small>{d.id}</small></span><ChevronRight size={15}/></button>)}</div><div className="panel-foot"><span className="dot"/> 空间浏览已就绪<small>单工单演示 · 支持指令控制</small></div></aside>
 {selected&&<div className="selected-card"><span className="eyebrow">{selected.id} / INSPECT</span><h2>{selected.title}</h2><p>绕行观察设备细节与工位空间</p><div><button onClick={()=>focus(selected)}><Focus size={15}/>聚焦</button>{selected.kind==='agv'&&<button onClick={()=>{engine.current?.ride(selected.id);setStatus('车载视角 · 随车辆移动，拖动转头');}}>车载视角 <ArrowUpRight size={15}/></button>}<button aria-label="关闭设备详情" onClick={()=>{setSelected(null);engine.current?.clearSelection();}}>关闭</button></div></div>}
 {mode==='walk'&&<><span className="crosshair">+</span>{!locked&&<button className="walk-resume" onClick={()=>engine.current?.lockPointer()}>点击画面继续漫游 <MousePointer2 size={16}/></button>}<div className="walk-pad">{['↑','←','↓','→'].map((v,i)=><button key={v} aria-label={['前进','左移','后退','右移'][i]} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);engine.current?.key(['KeyW','KeyA','KeyS','KeyD'][i],true);}} onPointerUp={()=>engine.current?.key(['KeyW','KeyA','KeyS','KeyD'][i],false)} onPointerCancel={()=>engine.current?.key(['KeyW','KeyA','KeyS','KeyD'][i],false)}>{v}</button>)}</div></>}
 {!ready&&<div className="loading"><Box size={32}/><p>{status}</p></div>}
 <div className="bottom-tools"><span><Scan size={15}/>{mode==='walk'?'第一人称 · 视高 1.68 m':mode==='ride'?'车载观察':mode==='follow'?'跟随 '+(selected?.id??'搬运车'):mode==='focus'?'设备近景':'自由观察'}</span><button disabled={!ready} onClick={()=>engine.current?.overview()}><RotateCcw size={15}/>回到全景</button></div>
 <div className="hint" role="status">{status}</div></section><footer><span>BUILT WITH CODEX <b>/</b> 把想法，带进空间</span><span>04 — 指令控制</span></footer></main>
}

