import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
await fs.mkdir('.qa',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1600,height:1000},deviceScaleFactor:1,acceptDownloads:true});
const page=await context.newPage(),errors=[],checks=[];page.setDefaultTimeout(20000);
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const log=name=>{checks.push(name);console.log('PASS',name);};
const state=()=>page.evaluate(()=>window.__studio.getProject());
const data=()=>page.evaluate(()=>window.__studio.getRenderer());
async function world(x,y){const p=await page.evaluate(({x,y})=>{const svg=document.querySelector('#plan'),p=svg.createSVGPoint();p.x=x;p.y=y;const q=p.matrixTransform(svg.getScreenCTM());return{x:q.x,y:q.y};},{x,y});await page.mouse.click(p.x,p.y);}
async function fileAction(name){await page.locator('#fileMenu').click();await page.locator(`[data-file="${name}"]`).click();if(['new','villa','reference'].includes(name))await page.locator('#confirmAction').click();}
async function waitFor(fn,arg){await page.waitForFunction(fn,arg,{timeout:20000});}
async function saveDownload(format){const promise=page.waitForEvent('download');if(format==='json'){await fileAction('save');}else{await page.locator('#exportMenu').click();await page.locator(`[data-export="${format}"]`).click();}const d=await promise,p=path.resolve('.qa',`export.${format}`);await d.saveAs(p);return p;}
function makePdf(){const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 450] /Resources << >> /Contents 4 0 R >>'];const stream='0 0 0 RG 10 w 50 50 500 350 re S 300 50 m 300 400 l S';objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);let s='%PDF-1.4\n',offset=[0];objects.forEach((o,i)=>{offset.push(Buffer.byteLength(s));s+=`${i+1} 0 obj\n${o}\nendobj\n`;});const start=Buffer.byteLength(s);s+='xref\n0 5\n0000000000 65535 f \n'+offset.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${start}\n%%EOF`;return s;}
try{
 await page.goto('http://127.0.0.1:4178/',{waitUntil:'networkidle'});await fileAction('villa');await waitFor(()=>window.__studio?.getRenderer()?.calls>0);assert.equal((await state()).floors.length,2);assert.ok((await data()).triangles>10000);await page.screenshot({path:'.qa/workspace.png'});log('real WebGL scene renders the two-floor example');
 await page.locator('#explode').click();await page.screenshot({path:'.qa/exploded.png'});await page.locator('#explode').click();log('floor explosion toggles');
 await fileAction('new');await page.locator('[data-view="2d"]').click();await page.locator('[data-tool="room"]').click();await world(1,1);await world(7,5);assert.equal((await state()).floors[0].walls.length,4);assert.equal((await state()).floors[0].rooms.length,1);log('draw a room using two clicks');
 await page.locator('[data-tool="door"]').click();await world(3,5);assert.equal((await state()).floors[0].openings.length,1);await page.locator('[data-tool="window"]').click();await world(4,1);assert.equal((await state()).floors[0].openings.length,2);log('place real door and window openings');
 await page.locator('[data-tool="select"]').click();await world(2,1);await page.getByLabel('长度 / m',{exact:true}).fill('8');await page.getByLabel('长度 / m',{exact:true}).press('Tab');let s=await state();assert.equal(s.floors[0].rooms.length,1);assert.ok(s.floors[0].walls.some(w=>Math.abs(w.b.x-9)<.01));log('edit wall length and preserve connected room');
 await page.locator('#undo').click();s=await state();assert.ok(s.floors[0].walls.every(w=>w.a.x<8&&w.b.x<8));await page.locator('#redo').click();assert.ok((await state()).floors[0].walls.some(w=>w.b.x>8));log('undo and redo geometry edits');
 await page.locator('[data-tool="stairs"]').click();await world(5,3);assert.equal((await state()).floors[0].stairs.length,1);
 await page.locator('#duplicateFloor').click();assert.equal((await state()).floors.length,2);await page.locator('#roof').selectOption('gable');await page.locator('[data-view="3d"]').click();await page.locator('#fit3d').click();await page.screenshot({path:'.qa/edited-model.png'});log('stairs, duplicate floor and roof are editable');
 await page.locator('[data-tool="furniture"]').click();await page.locator('[data-item="0"]').click();await world(3,3);assert.equal((await state()).floors[1].furniture.length,1);log('original furniture library places a real model');
 await page.getByLabel('项目名称').fill('浏览器回归样例');await page.getByLabel('项目名称').press('Tab');await page.waitForFunction(()=>document.querySelector('#saveState').textContent.includes('已保存'));const json=await saveDownload('json');const exported=JSON.parse(await fs.readFile(json,'utf8'));assert.equal(exported.floors.length,2);await page.reload({waitUntil:'networkidle'});await waitFor(()=>window.__studio?.getProject()?.name==='浏览器回归样例');assert.equal((await state()).floors[1].furniture.length,1);log('complete JSON export and IndexedDB restore');
 const glb=await saveDownload('glb');const buffer=await fs.readFile(glb);assert.equal(buffer.toString('ascii',0,4),'glTF');assert.equal(buffer.readUInt32LE(8),buffer.length);const stl=await saveDownload('stl');const stb=await fs.readFile(stl);assert.equal(stb.length,84+stb.readUInt32LE(80)*50);log('GLB and STL produce valid binary files');
 await page.locator('[data-view="3d"]').click();await page.locator('#walk').click();assert.equal((await data()).walk,true);const before=(await data()).camera;await page.keyboard.down('KeyW');await page.waitForTimeout(450);await page.keyboard.up('KeyW');const after=(await data()).camera;assert.ok(Math.hypot(after[0]-before[0],after[2]-before[2])>.1);await page.screenshot({path:'.qa/walkthrough.png'});await page.locator('#exitWalk').click();log('walkthrough accepts actual keyboard movement');
 // Import the previously exported project through the file input, then verify malformed data is harmless.
 await page.locator('#projectFile').setInputFiles(json);assert.equal((await state()).name,'浏览器回归样例');await page.locator('#projectFile').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{"version":2,"floors":[]}')});assert.equal((await state()).name,'浏览器回归样例');log('project import round-trips and rejects malformed input');
 const png=await page.evaluate(()=>{const cv=document.createElement('canvas');cv.width=800;cv.height=600;const c=cv.getContext('2d');c.fillStyle='white';c.fillRect(0,0,800,600);c.fillStyle='black';[[60,60,680,12],[60,60,12,480],[728,60,12,480],[60,528,290,12],[430,528,310,12],[300,60,12,480]].forEach(r=>c.fillRect(...r));return cv.toDataURL('image/png').split(',')[1];});await fs.writeFile('.qa/plan.png',Buffer.from(png,'base64'));
 await fileAction('new');await page.locator('#importPlan').click();await page.locator('#planFile').setInputFiles(path.resolve('.qa/plan.png'));await page.waitForFunction(()=>window.__studio.getProject().floors[0].image);assert.equal((await state()).floors[0].image.pixelWidth,800);await page.locator('#calibrate').click();await world(2,7);await world(12,7);await page.locator('#knownUnit').selectOption('m');await page.locator('#knownLength').fill('12');await page.locator('#applyCalibrate').click();s=await state();assert.equal(s.floors[0].image.calibrated,true);assert.ok(Math.abs(s.floors[0].image.width-18)<.2);log('image import and two-point metric calibration');
 await page.locator('#recognize').click();await page.locator('#runDetect').click();await page.locator('#applyDetect').waitFor({state:'visible'});await page.locator('#applyDetect').click();s=await state();assert.ok(s.floors[0].walls.length>=4);assert.ok(s.floors[0].openings.length>=1);await page.locator('[data-view="split"]').click();await page.locator('#fit3d').click();await page.screenshot({path:'.qa/recognized.png'});log('local raster recognition adds editable wall and opening geometry');
 await fs.writeFile('.qa/plan.pdf',makePdf());await page.locator('#importPlan').click();await page.locator('#planFile').setInputFiles(path.resolve('.qa/plan.pdf'));await page.waitForFunction(()=>window.__studio.getProject().floors[0].image?.name==='plan.pdf');assert.ok((await state()).floors[0].image.pixelWidth>500);log('PDF parses and renders into a usable plan underlay');
 await fileAction('reference');await page.locator('[data-view="3d"]').click();await page.locator('#fit3d').click();await page.waitForFunction(()=>window.__studio.getRenderer()?.triangles>10000);assert.ok((await state()).floors[0].furniture.length>30);await page.screenshot({path:'.qa/reference-reuse.png'});log('original floorplan and detailed furniture render in the new engine');
 await page.setViewportSize({width:390,height:844});await page.locator('#fit3d').click();await page.screenshot({path:'.qa/mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#toggleInspector').click();assert.equal(await page.locator('#inspector').isVisible(),true);await page.locator('#toggleInspector').click();log('mobile layout and property drawer remain accessible');
 assert.deepEqual(errors,[]);log('no browser JavaScript or WebGL console errors');
 await fs.writeFile('.qa/browser-results.json',JSON.stringify({passed:checks.length,checks,errors},null,2));
 console.log(JSON.stringify({passed:checks.length,errors},null,2));
}catch(e){console.error(e);await page.screenshot({path:'.qa/failure.png'});await fs.writeFile('.qa/failure.json',JSON.stringify({checks,errors,error:e.message,project:await state().catch(()=>null)},null,2));process.exitCode=1;}finally{await browser.close();}
