import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import * as M from '../src/model.js';
const p=M.blankProject(),f=p.floors[0];p.name='楼梯验证';[[0,0,12,0],[12,0,12,9],[12,9,0,9],[0,9,0,0]].forEach(q=>f.walls.push(M.wall({x:q[0],y:q[1]},{x:q[2],y:q[3]})));f.rooms=M.detectRooms(f);f.stairs=[{id:M.uid(),x:6,y:4.5,w:1.6,d:4,rot:0}];const upper=M.duplicateFloor(f,'二层');upper.stairs=[];p.floors.push(upper);
const browser=await chromium.launch({headless:true,args:['--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const data=()=>page.evaluate(()=>window.__studio.getRenderer());
async function face(yaw){const r=await data(),diff=Math.atan2(Math.sin(r.rotation[1]-yaw),Math.cos(r.rotation[1]-yaw));const b=await page.locator('#three canvas').boundingBox(),x=b.x+b.width/2,y=b.y+b.height/2;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+diff/.004,y,{steps:10});await page.mouse.up();}
async function go(x,z){const r=await data(),dx=x-r.camera[0],dz=z-r.camera[2];await face(Math.atan2(-dx,-dz));await page.keyboard.down('KeyW');try{await page.waitForFunction(({x,z})=>{const p=window.__studio.getRenderer().camera;return Math.hypot(p[0]-x,p[2]-z)<.15;},{x,z},{timeout:20000});}finally{await page.keyboard.up('KeyW');}}
try{await page.goto('http://127.0.0.1:4178/',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__studio);await page.locator('#projectFile').setInputFiles({name:'stairs.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(p))});await page.waitForFunction(()=>window.__studio.getProject().name==='楼梯验证');await page.locator('#walk').click();await go(6,6.75);await go(6,2.15);let r=await data();assert.equal(r.floorId,upper.id);assert.ok(Math.abs(r.camera[1]-4.4)<.1);console.log('PASS walk up actual stairs to upper floor');await page.screenshot({path:'.qa/upstairs.png'});await go(6,6.8);r=await data();assert.equal(r.floorId,f.id);assert.ok(Math.abs(r.camera[1]-1.6)<.1);console.log('PASS walk down actual stairs to ground floor');await face(Math.PI);await page.keyboard.down('KeyW');await page.waitForTimeout(3500);await page.keyboard.up('KeyW');r=await data();assert.ok(r.camera[2]<8.8&&r.camera[2]>8.6);console.log('PASS solid wall blocks walking');assert.deepEqual(errors,[]);await fs.writeFile('.qa/stairs-results.json',JSON.stringify({upstairs:true,downstairs:true,wallCollision:true,errors},null,2));}catch(e){console.error(e);console.log(await data());await page.screenshot({path:'.qa/stairs-failure.png'});process.exitCode=1;}finally{await browser.close();}
