import './air.css';
import { Arena } from './arena';
import { HandInput } from './hand-input';
import { Game, type InputMode } from './game';
const $ = <T extends HTMLElement = HTMLElement>(s: string) => document.querySelector<T>(s)!;
$('#app').innerHTML = `
<header class="topbar"><a class="brand" href="/" aria-label="隔空抓取实验室"><span class="brand-symbol" aria-hidden="true"><svg viewBox="0 0 32 32" fill="none"><path d="M11 11H7a4 4 0 1 1 4-4v18a4 4 0 1 1-4-4h18a4 4 0 1 1-4 4V7a4 4 0 1 1 4 4H11Z"/></svg></span><span>AIR<span class="brand-light"> / LAB</span><small>人工智能互动实验室</small></span></a><div class="experiment">EXPERIMENT 01 <span>视觉 × 控制</span></div><button class="icon-btn" id="fullscreen" title="全屏展示">⛶ <span>全屏</span></button></header>
<main id="main-content" class="workspace"><section class="stage-column">
<div class="arena-wrap" id="arena-wrap"><div id="arena" aria-label="三维机械臂操作区域，鼠标移动瞄准，按住抓取、松开放置，或方向键与空格操作" tabindex="0"></div><div id="toast" class="toast" role="status" aria-live="polite">移动到方块上方，按住抓取</div><div class="arena-bottom"><span><i class="cyan-dot"></i> 夹爪落点</span><span><i class="yellow-dot"></i> 发光区域 = 投放区</span><span>3D LIVE</span></div><div id="result" class="result hidden"><div class="result-card"><div class="eyebrow">CHALLENGE COMPLETE</div><h2>挑战完成</h2><p>每一次准确放置，都是一次人机协作。</p><div class="result-score"><strong id="final-score">0</strong><span>分</span></div><div id="final-detail"></div><button id="again" class="primary">再挑战一次 ↗</button><button id="practice-after" class="text-btn">回到自由练习</button></div></div></div>
<div class="instruction-strip"><div><b>01</b><span>移动手掌<small>控制夹爪的位置</small></span><span class="step-glyph" aria-hidden="true"><svg viewBox="0 0 48 48"><path d="M17 26V13a2.5 2.5 0 0 1 5 0v10-14a2.5 2.5 0 0 1 5 0v14-12a2.5 2.5 0 0 1 5 0v13-8a2.5 2.5 0 0 1 5 0v15c0 8-4 12-10 12h-2c-4 0-7-2-9-5l-7-10c-2-3 2-6 4-3l4 4"/><path d="M4 15h8M7 12l-3 3 3 3M39 15h6m-3-3 3 3-3 3"/></svg></span></div><div><b>02</b><span>捏合手指<small>拇指 + 食指，抓起方块</small></span><span class="step-glyph" aria-hidden="true"><svg viewBox="0 0 48 48"><path d="M18 42c-2-5-4-8-7-11l-4-4c-3-3 1-6 4-4l7 5V11c0-6 9-6 9 0v6c0 3-3 5-6 4l-3-2M27 24v-7c0-4 6-4 6 0v9-6c0-4 6-4 6 0v9-5c0-4 5-4 5 0v7c0 5-2 8-5 11"/><path d="m8 9 4 3m-1-9 3 4M5 17h5"/></svg></span></div><div><b>03</b><span>松开放置<small>投进发光区域，+10 分</small></span><span class="step-glyph" aria-hidden="true"><svg viewBox="0 0 48 48"><path d="m14 29-6-7c-2-3 2-6 4-3l5 5-3-14c-1-4 4-5 5-1l3 12-1-15c0-4 5-4 5 0l1 15 2-13c1-4 6-3 5 1l-2 14 4-9c2-3 6-1 4 2l-5 14c-1 4-4 6-8 6h-4c-4 0-7-3-9-7Z"/><path d="M17 39v7m-3-3 3 3 3-3m12-4v7m-3-3 3 3 3-3"/></svg></span></div></div></section>
<aside class="control-column"><section class="panel score-panel"><div class="panel-heading"><h2>挑战记录</h2><span id="round-state" class="small-tag">自由练习</span></div><div class="stats"><div><span>本轮得分</span><strong id="score">000</strong><small>每次成功 +10</small></div><div class="timer-stat"><span>剩余时间</span><strong id="timer">60<span>s</span></strong><small>60 秒挑战</small></div></div><div class="time-track"><div id="time-fill"></div></div><button class="primary" id="start">开始 60 秒挑战 <span>↗</span></button><button class="secondary hidden" id="pause">暂停挑战</button></section>
<section class="panel camera-panel"><div class="panel-heading"><h2>AI 视觉</h2><span id="camera-badge" class="small-tag">摄像头未开启</span></div><div class="camera-screen"><video id="video" playsinline muted></video><canvas id="hand-canvas"></canvas><div class="camera-placeholder" id="camera-placeholder"><span class="camera-icon">⌖</span><strong>让机器看见你的手</strong><span>开启后显示手部关键点</span></div><div class="camera-corners"></div><span class="camera-caption">LOCAL VISION / 21 LANDMARKS</span></div><p id="camera-status" class="camera-status" role="status">图像仅在本机处理，不上传、不录像。</p><button class="camera-button" id="camera">开启摄像头 <span>◎</span></button><button class="text-btn hidden" id="mouse">关闭摄像头，使用鼠标</button><div class="gesture-readout"><span>当前动作</span><strong id="gesture">等待输入</strong><i id="gesture-light"></i></div></section>
</aside></main><footer><span>BUILT WITH CODEX <i> / </i> 用 AI 创造，让控制发生</span></footer>`;
const game = new Game();
let arena: Arena;
try { arena = new Arena($('#arena'), game); } catch { $('#arena').innerHTML = '<div class="render-error">三维画面启动失败，请使用支持 WebGL 的 Chrome 或 Edge 浏览器，并开启硬件加速。</div>'; throw new Error('WebGL unavailable'); }
let modelReady = false; let modelMessage = '正在加载 Blender 机械臂模型…';
void arena.ready.then(() => { modelReady = true; }).catch(() => { modelMessage = '模型加载失败，请刷新页面重试。'; });
let mode: InputMode = 'mouse'; let cameraRunning = false; let cameraBusy = false; let audioContext: AudioContext | null = null; let lastMessage = '';
const status = (text: string) => { $('#camera-status').textContent = text; };
const hand = new HandInput($('#video'), $('#hand-canvas'), {
 status,
 frame: (frame) => { if (mode !== 'hand') return; game.tracked = frame !== null; if (!frame) { $('#gesture').textContent = '未看到手'; $('#gesture-light').classList.remove('active'); return; } game.setTarget(frame.x, frame.z); game.setGrip(frame.pinch); $('#gesture').textContent = frame.pinch ? '捏合 · 抓取' : '张开 · 移动'; $('#gesture-light').classList.toggle('active', frame.pinch); },
 lost: () => { if (mode === 'hand' && game.state === 'running') { game.pause(); status('手部跟踪中断，挑战已暂停。手回到画面后，点击继续。'); } },
 ended: () => { if (cameraRunning) { disableCamera(); status('摄像头已断开，已切换为鼠标操作。'); } },
});
function beep(success: boolean) { try { audioContext ??= new AudioContext(); void audioContext.resume(); const osc = audioContext.createOscillator(); const gain = audioContext.createGain(); osc.connect(gain); gain.connect(audioContext.destination); osc.frequency.setValueAtTime(success ? 660 : 220, audioContext.currentTime); osc.frequency.exponentialRampToValueAtTime(success ? 1040 : 150, audioContext.currentTime + .13); gain.gain.setValueAtTime(.04, audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audioContext.currentTime + .2); osc.start(); osc.stop(audioContext.currentTime + .2); } catch { /* Audio is optional. */ } }
game.onEvent = (event) => { if (event === 'score') { arena.celebrate(); beep(true); } if (event === 'miss') beep(false); };
function start() { if (!modelReady) return; if (mode === 'hand' && !game.tracked) { status('请先把一只手放进画面，识别成功后再开始。'); return; } game.start(); $('#result').classList.add('hidden'); }
$('#start').onclick = start; $('#again').onclick = start; $('#practice-after').onclick = () => { game.reset(); $('#result').classList.add('hidden'); };
$('#pause').onclick = () => { if (game.state === 'paused') { if (mode === 'hand' && !game.tracked) { status('请先让手回到画面。'); return; } game.resume(); } else game.pause(); };
$('#camera').onclick = async () => { if (cameraBusy) return; if (cameraRunning) { disableCamera(); return; } cameraBusy = true; const btn = $('#camera') as HTMLButtonElement; btn.disabled = true; btn.textContent = '正在启动识别…'; if (game.state === 'running') game.pause(); try { await hand.start(); cameraRunning = true; mode = 'hand'; game.mode = mode; game.tracked = false; game.clearGrip(); $('#camera-placeholder').classList.add('hidden'); $('#camera-badge').textContent = '本机识别中'; $('#camera-badge').classList.add('online'); $('#mouse').classList.remove('hidden'); btn.textContent = '关闭摄像头'; } catch (error) { status(error instanceof Error ? error.message : '启动失败，请重试。'); btn.textContent = '重新开启摄像头'; } finally { cameraBusy = false; btn.disabled = false; } };
function disableCamera() { cameraRunning = false; hand.stop(); mode = 'mouse'; game.mode = mode; game.tracked = true; game.clearGrip(); if (game.state === 'running') game.pause(); $('#camera-placeholder').classList.remove('hidden'); $('#camera-badge').textContent = '摄像头未开启'; $('#camera-badge').classList.remove('online'); $('#mouse').classList.add('hidden'); $('#camera').textContent = '开启摄像头 ◎'; $('#gesture').textContent = '鼠标操作'; status('摄像头已关闭。图像仅在本机处理，不上传、不录像。'); }
$('#mouse').onclick = disableCamera;
$('#fullscreen').onclick = () => { const p = document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen(); void p.catch(() => { $('#toast').textContent = '浏览器暂不支持全屏，可按 F11。'; }); };
const surface = $('#arena');
surface.onpointermove = (e) => { if (mode === 'mouse') { if (e.buttons === 0) game.setGrip(false); const p = arena.pointerToWorld(e.clientX, e.clientY); if (p) game.setTarget(p.x, p.z); } };
surface.onpointerdown = (e) => { if (mode !== 'mouse' || e.button !== 0) return; surface.focus(); surface.setPointerCapture(e.pointerId); const p = arena.pointerToWorld(e.clientX, e.clientY); if (p) game.setTarget(p.x, p.z); game.setGrip(true); };
surface.onpointerup = () => { if (mode === 'mouse') game.setGrip(false); };
surface.onpointercancel = () => { game.clearGrip(); if (game.state === 'running') game.pause(); };
surface.onkeydown = (e) => { if (mode !== 'mouse') return; if (e.code === 'Space') { e.preventDefault(); game.setGrip(true); } const moves: Record<string, [number, number]> = {ArrowLeft:[-.2,0],ArrowRight:[.2,0],ArrowUp:[0,-.2],ArrowDown:[0,.2]}; const move = moves[e.key]; if (move) { e.preventDefault(); game.setTarget(game.target.x+move[0],game.target.z+move[1]); } };
surface.onkeyup = (e) => { if (e.code === 'Space' && mode === 'mouse') { e.preventDefault(); game.setGrip(false); } };
window.addEventListener('blur', () => { game.clearGrip(); if (game.state === 'running') game.pause(); });
document.addEventListener('visibilitychange', () => { if (document.hidden) { if (game.state === 'running') game.pause(); game.clearGrip(); } });
window.addEventListener('pagehide', () => hand.stop());
let previous = performance.now(); let uiTime = 0;
function animate(now: number) { const dt = (now - previous) / 1000; previous = now; game.update(dt); arena.render(Math.min(dt,.05), now / 1000); if (now-uiTime>80) { uiTime=now; $('#score').textContent=String(game.score).padStart(3,'0'); $('#timer').innerHTML=`${Math.ceil(game.remaining)}<span>s</span>`; $('#time-fill').style.width=`${game.remaining/60*100}%`; $('#round-state').textContent=({practice:'自由练习',running:'挑战进行中',paused:'已暂停',finished:'挑战完成'} as const)[game.state]; $('#pause').classList.toggle('hidden',game.state!=='running'&&game.state!=='paused'); $('#pause').textContent=game.state==='paused'?'继续挑战':'暂停挑战'; ($('#start') as HTMLButtonElement).disabled=!modelReady||game.state==='running'||game.state==='paused'; const message=modelReady?game.message:modelMessage; if(message!==lastMessage){$('#toast').textContent=message;lastMessage=message;} if(game.state==='finished'){ $('#result').classList.remove('hidden'); $('#final-score').textContent=String(game.score); $('#final-detail').textContent=`成功放置 ${game.score/10} 次 · 尝试抓取 ${game.attempts} 次`; } } requestAnimationFrame(animate); }
requestAnimationFrame(animate);
