import './air.css';
import { Arena } from './arena';
import { HandInput } from './hand-input';
import { Game, type InputMode } from './game';
const $ = <T extends HTMLElement = HTMLElement>(s: string) => document.querySelector<T>(s)!;
$('#app').innerHTML = `
<header class="topbar"><a class="brand" href="/" aria-label="隔空抓取实验室"><span class="brand-symbol">⌘</span><span>AIR<span class="brand-light"> / LAB</span><small>人工智能互动实验室</small></span></a><div class="experiment">EXPERIMENT 01 <span>视觉 × 控制</span></div><button class="icon-btn" id="fullscreen" title="全屏展示">⛶ <span>全屏</span></button></header>
<main id="main-content" class="workspace"><section class="stage-column"><div class="stage-title"><div><div class="eyebrow"><i></i> HAND-TRACKED ROBOTICS</div><h1>隔空<span>抓取挑战</span></h1><p>伸出手，把想法变成动作。</p></div><div class="round-label">01<span>感知 · 判断 · 执行</span></div></div>
<div class="arena-wrap" id="arena-wrap"><div id="arena" aria-label="三维机械臂操作区域，鼠标移动瞄准，按住抓取、松开放置，或方向键与空格操作" tabindex="0"></div><div class="arena-top"><span class="live-tag"><i></i> <span id="mode-label">鼠标练习</span></span><span class="workspace-label">WORKSPACE / A–01</span></div><div id="toast" class="toast" role="status" aria-live="polite">移动到方块上方，按住抓取</div><div class="arena-bottom"><span><i class="cyan-dot"></i> 夹爪落点</span><span><i class="yellow-dot"></i> 发光区域 = 投放区</span><span>3D LIVE</span></div><div id="result" class="result hidden"><div class="result-card"><div class="eyebrow">CHALLENGE COMPLETE</div><h2>挑战完成</h2><p>每一次准确放置，都是一次人机协作。</p><div class="result-score"><strong id="final-score">0</strong><span>分</span></div><div id="final-detail"></div><button id="again" class="primary">再挑战一次 ↗</button><button id="practice-after" class="text-btn">回到自由练习</button></div></div></div>
<div class="instruction-strip"><div><b>01</b><span>移动手掌<small>控制夹爪的位置</small></span><span class="step-glyph">↔</span></div><div><b>02</b><span>捏合手指<small>拇指 + 食指，抓起方块</small></span><span class="step-glyph">⌁</span></div><div><b>03</b><span>松开放置<small>投进发光区域，+10 分</small></span><span class="step-glyph">◎</span></div></div></section>
<aside class="control-column"><section class="panel score-panel"><div class="panel-heading"><h2>挑战记录</h2><span id="round-state" class="small-tag">自由练习</span></div><div class="stats"><div><span>本轮得分</span><strong id="score">000</strong><small>每次成功 +10</small></div><div class="timer-stat"><span>剩余时间</span><strong id="timer">60<span>s</span></strong><small>60 秒挑战</small></div></div><div class="time-track"><div id="time-fill"></div></div><button class="primary" id="start">开始 60 秒挑战 <span>↗</span></button><button class="secondary hidden" id="pause">暂停挑战</button></section>
<section class="panel camera-panel"><div class="panel-heading"><h2>AI 视觉</h2><span id="camera-badge" class="small-tag">摄像头未开启</span></div><div class="camera-screen"><video id="video" playsinline muted></video><canvas id="hand-canvas"></canvas><div class="camera-placeholder" id="camera-placeholder"><span class="camera-icon">⌖</span><strong>让机器看见你的手</strong><span>开启后显示手部关键点</span></div><div class="camera-corners"></div><span class="camera-caption">LOCAL VISION / 21 LANDMARKS</span></div><p id="camera-status" class="camera-status" role="status">图像仅在本机处理，不上传、不录像。</p><button class="camera-button" id="camera">开启摄像头 <span>◎</span></button><button class="text-btn hidden" id="mouse">关闭摄像头，使用鼠标</button><div class="gesture-readout"><span>当前动作</span><strong id="gesture">等待输入</strong><i id="gesture-light"></i></div></section>
<section class="panel insight-panel"><div class="panel-heading"><h2>机器如何理解你</h2><span class="small-tag">实时链路</span></div><div class="pipeline"><div><i id="sense-dot"></i><span>感知</span><small>识别手部位置</small></div><b>↓</b><div><i id="think-dot"></i><span>判断</span><small>移动 / 捏合 / 松开</small></div><b>↓</b><div><i class="active"></i><span>执行</span><small id="action">夹爪就绪</small></div></div></section></aside></main><footer><span>BUILT WITH CODEX <i> / </i> 用 AI 创造，让控制发生</span><span id="footer-tip">鼠标移动 · 按住抓取 · 松开放置　｜　方向键 + 空格也可操作</span></footer>`;
const game = new Game();
let arena: Arena;
try { arena = new Arena($('#arena'), game); } catch { $('#arena').innerHTML = '<div class="render-error">三维画面启动失败，请使用支持 WebGL 的 Chrome 或 Edge 浏览器，并开启硬件加速。</div>'; throw new Error('WebGL unavailable'); }
let modelReady = false; let modelMessage = '正在加载 Blender 机械臂模型…';
void arena.ready.then(() => { modelReady = true; }).catch(() => { modelMessage = '模型加载失败，请刷新页面重试。'; });
let mode: InputMode = 'mouse'; let cameraRunning = false; let cameraBusy = false; let audioContext: AudioContext | null = null; let lastMessage = '';
const status = (text: string) => { $('#camera-status').textContent = text; };
const hand = new HandInput($('#video'), $('#hand-canvas'), {
 status,
 frame: (frame) => { if (mode !== 'hand') return; game.tracked = frame !== null; if (!frame) { $('#gesture').textContent = '未看到手'; $('#gesture-light').classList.remove('active'); $('#sense-dot').classList.remove('active'); $('#think-dot').classList.remove('active'); return; } game.setTarget(frame.x, frame.z); game.setGrip(frame.pinch); $('#gesture').textContent = frame.pinch ? '捏合 · 抓取' : '张开 · 移动'; $('#gesture-light').classList.toggle('active', frame.pinch); $('#sense-dot').classList.add('active'); $('#think-dot').classList.add('active'); },
 lost: () => { if (mode === 'hand' && game.state === 'running') { game.pause(); status('手部跟踪中断，挑战已暂停。手回到画面后，点击继续。'); } },
 ended: () => { if (cameraRunning) { disableCamera(); status('摄像头已断开，已切换为鼠标操作。'); } },
});
function beep(success: boolean) { try { audioContext ??= new AudioContext(); void audioContext.resume(); const osc = audioContext.createOscillator(); const gain = audioContext.createGain(); osc.connect(gain); gain.connect(audioContext.destination); osc.frequency.setValueAtTime(success ? 660 : 220, audioContext.currentTime); osc.frequency.exponentialRampToValueAtTime(success ? 1040 : 150, audioContext.currentTime + .13); gain.gain.setValueAtTime(.04, audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audioContext.currentTime + .2); osc.start(); osc.stop(audioContext.currentTime + .2); } catch { /* Audio is optional. */ } }
game.onEvent = (event) => { if (event === 'score') { arena.celebrate(); beep(true); } if (event === 'miss') beep(false); };
function start() { if (!modelReady) return; if (mode === 'hand' && !game.tracked) { status('请先把一只手放进画面，识别成功后再开始。'); return; } game.start(); $('#result').classList.add('hidden'); }
$('#start').onclick = start; $('#again').onclick = start; $('#practice-after').onclick = () => { game.reset(); $('#result').classList.add('hidden'); };
$('#pause').onclick = () => { if (game.state === 'paused') { if (mode === 'hand' && !game.tracked) { status('请先让手回到画面。'); return; } game.resume(); } else game.pause(); };
$('#camera').onclick = async () => { if (cameraBusy) return; if (cameraRunning) { disableCamera(); return; } cameraBusy = true; const btn = $('#camera') as HTMLButtonElement; btn.disabled = true; btn.textContent = '正在启动识别…'; if (game.state === 'running') game.pause(); try { await hand.start(); cameraRunning = true; mode = 'hand'; game.mode = mode; game.tracked = false; game.clearGrip(); $('#camera-placeholder').classList.add('hidden'); $('#camera-badge').textContent = '本机识别中'; $('#camera-badge').classList.add('online'); $('#mouse').classList.remove('hidden'); $('#mode-label').textContent = '手势控制'; $('#footer-tip').textContent = '手掌左右 / 上下移动 · 捏合抓取 · 松开放置'; btn.textContent = '关闭摄像头'; } catch (error) { status(error instanceof Error ? error.message : '启动失败，请重试。'); btn.textContent = '重新开启摄像头'; } finally { cameraBusy = false; btn.disabled = false; } };
function disableCamera() { cameraRunning = false; hand.stop(); mode = 'mouse'; game.mode = mode; game.tracked = true; game.clearGrip(); if (game.state === 'running') game.pause(); $('#camera-placeholder').classList.remove('hidden'); $('#camera-badge').textContent = '摄像头未开启'; $('#camera-badge').classList.remove('online'); $('#mouse').classList.add('hidden'); $('#camera').textContent = '开启摄像头 ◎'; $('#mode-label').textContent = '鼠标练习'; $('#gesture').textContent = '鼠标操作'; $('#footer-tip').textContent = '鼠标移动 · 按住抓取 · 松开放置　｜　方向键 + 空格也可操作'; status('摄像头已关闭。图像仅在本机处理，不上传、不录像。'); }
$('#mouse').onclick = disableCamera;
$('#fullscreen').onclick = () => { const p = document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen(); void p.catch(() => { $('#toast').textContent = '浏览器暂不支持全屏，可按 F11。'; }); };
const surface = $('#arena');
surface.onpointermove = (e) => { if (mode === 'mouse') { if (e.buttons === 0) game.setGrip(false); const p = arena.pointerToWorld(e.clientX, e.clientY); if (p) game.setTarget(p.x, p.z); } };
surface.onpointerdown = (e) => { if (mode !== 'mouse' || e.button !== 0) return; surface.focus(); surface.setPointerCapture(e.pointerId); const p = arena.pointerToWorld(e.clientX, e.clientY); if (p) game.setTarget(p.x, p.z); game.setGrip(true); };
surface.onpointerup = () => { if (mode === 'mouse') game.setGrip(false); };
surface.onpointercancel = () => { game.clearGrip(); if (game.state === 'running') game.pause(); };
surface.onkeydown = (e) => { if (mode !== 'mouse') return; if (e.code === 'Space') { e.preventDefault(); game.setGrip(true); } const moves: Record<string, [number, number]> = {ArrowLeft:[-.2,0],ArrowRight:[.2,0],ArrowUp:[0,-.2],ArrowDown:[0,.2]}; const move = moves[e.key]; if (move) { e.preventDefault(); game.setTarget(game.target.x+move[0],game.target.z+move[1]); } };
surface.onkeyup = (e) => { if (e.code === 'Space' && mode === 'mouse') { e.preventDefault(); game.setGrip(false); } };
window.addEventListener('blur', () => { game.clearGrip(); if (game.state === 'running') game.pause(); });
document.addEventListener('visibilitychange', () => { if (document.hidden) { if (game.state === 'running') game.pause(); game.clearGrip(); } });
window.addEventListener('pagehide', () => hand.stop());
let previous = performance.now(); let uiTime = 0;
function animate(now: number) { const dt = (now - previous) / 1000; previous = now; game.update(dt); arena.render(Math.min(dt,.05), now / 1000); if (now-uiTime>80) { uiTime=now; $('#score').textContent=String(game.score).padStart(3,'0'); $('#timer').innerHTML=`${Math.ceil(game.remaining)}<span>s</span>`; $('#time-fill').style.width=`${game.remaining/60*100}%`; $('#round-state').textContent=({practice:'自由练习',running:'挑战进行中',paused:'已暂停',finished:'挑战完成'} as const)[game.state]; $('#pause').classList.toggle('hidden',game.state!=='running'&&game.state!=='paused'); $('#pause').textContent=game.state==='paused'?'继续挑战':'暂停挑战'; ($('#start') as HTMLButtonElement).disabled=!modelReady||game.state==='running'||game.state==='paused'; const message=modelReady?game.message:modelMessage; if(message!==lastMessage){$('#toast').textContent=message;lastMessage=message;} $('#action').textContent=game.held!==null?'正在搬运方块':game.phase==='down'?'夹爪下降':game.phase==='drop'?'正在放置':'夹爪跟随目标'; if(game.state==='finished'){ $('#result').classList.remove('hidden'); $('#final-score').textContent=String(game.score); $('#final-detail').textContent=`成功放置 ${game.score/10} 次 · 尝试抓取 ${game.attempts} 次`; } } requestAnimationFrame(animate); }
requestAnimationFrame(animate);
