import React,{useEffect,useRef,type ReactNode} from 'react';
import {Archive,Check,Radio} from 'lucide-react';
export const lunarUiAsset=(name:string)=>`/moon/content/ui/${name}`;
export function useTerminalFocus(){
 const ref=useRef<HTMLElement|null>(null);
 useEffect(()=>{const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;const root=ref.current;if(!root)return;
 const controls=()=>Array.from(root.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),a[href],[tabindex="0"]')).filter(el=>el.getClientRects().length>0);
 (root.querySelector<HTMLElement>('[data-terminal-close]')??controls()[0])?.focus({preventScroll:true});
 const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const items=controls(),first=items[0],last=items.at(-1);if(!first)return;if(e.shiftKey&&(document.activeElement===first||!root.contains(document.activeElement))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||!root.contains(document.activeElement))){e.preventDefault();first.focus();}};
 root.addEventListener('keydown',trap);return()=>{root.removeEventListener('keydown',trap);if(previous?.isConnected)previous.focus({preventScroll:true});};},[]);return ref;
}
export function SignalWave({active=false}:{active?:boolean}){return <img className={'moon-radio-wave'+(active?' is-transmitting':'')} src={lunarUiAsset('signal-wave.svg')} alt="" aria-hidden="true"/>;}
export function ArchiveReward({title,children,onRead}:{title:string;children?:ReactNode;onRead:()=>void}){return <div className="moon-discovery"><div className="moon-discovery-seal"><Archive size={27}/><Check size={14}/></div><div><small>档案已解锁</small><h3>{title}</h3>{children}<button onClick={onRead}>阅读档案 <span aria-hidden="true">→</span></button></div></div>;}
export function Receiver({value,min,max,target,step=1,unit,label,tolerance=.05,onChange}:{value:number;min:number;max:number;target:number;step?:number;unit:string;label:string;tolerance?:number;onChange:(value:number)=>void}){
 const locked=Math.abs(value-target)<=tolerance,marker=20+460*(value-min)/(max-min),peak=20+460*(target-min)/(max-min),digits=step<1?1:0;
 const path=Array.from({length:161},(_,i)=>{const x=20+i*460/160,y=143-102*Math.exp(-Math.pow((x-peak)/12,2))-5*Math.abs(Math.sin(i*2.71))-3*Math.abs(Math.cos(i*.77));return `${i?'L':'M'}${x.toFixed(2)} ${y.toFixed(2)}`;}).join(' ');
 return <section className={'moon-receiver'+(locked?' is-locked':'')} aria-label={label}><header><Radio size={18}/><span>{unit==='V'?'POWER CONTROL':'FIELD RECEIVER'}</span><small>{label}</small></header><div className="moon-receiver-value"><output aria-label={label+'读数'}>{value.toFixed(digits)}</output><span>{unit}</span><b>{locked?(unit==='V'?'电压已校准':'载波已锁定'):(unit==='V'?'调整输出电压':'搜索载波')}</b></div><svg className="moon-frequency-spectrum" viewBox="0 0 500 178" role="img" aria-label={`目标 ${target} ${unit}，当前 ${value.toFixed(digits)} ${unit}`}><g className="moon-spectrum-grid">{[20,66,112,158,204,250,296,342,388,434,480].map(x=><path key={x} d={`M${x} 12V152`}/>)}{[24,56,88,120,152].map(y=><path key={y} d={`M20 ${y}H480`}/>)}</g><path className="moon-spectrum-wave" d={path}/><path className="moon-spectrum-marker" d={`M${marker} 10V153`}/><circle className="moon-spectrum-dot" cx={marker} cy="11" r="2.5"/><g className="moon-spectrum-labels"><text x="20" y="173">{min.toFixed(digits)}</text><text x={peak} y="173" textAnchor="middle">{target.toFixed(digits)}</text><text x="480" y="173" textAnchor="end">{max.toFixed(digits)}</text></g></svg><label className="moon-tuning-control"><span>{label}</span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><i aria-hidden="true" style={{transform:`rotate(${(value-min)/(max-min)*270-135}deg)`}}/></label></section>;
}
