'use client';
import {useEffect,useState} from 'react';
import {fieldSites,fieldRoutes,type FieldSiteId,type NavTarget} from './moon-exploration';
import {powerProfiles,type PowerMode} from './moon-systems';
export function ExpeditionPanel({voiceVolume=1,discoveries,playerX,playerZ,navTarget,powerMode,solarRepaired,complete,onNavigate,onPower,onLaunch,onClose}:{voiceVolume?:number;discoveries:FieldSiteId[];playerX:number;playerZ:number;navTarget:NavTarget;powerMode:PowerMode;solarRepaired:boolean;complete:boolean;onNavigate:(target:NavTarget)=>void;onPower:(mode:PowerMode)=>void;onLaunch:()=>void;onClose:()=>void}){
 const [notice,setNotice]=useState('');useEffect(()=>()=>{if('speechSynthesis' in window)window.speechSynthesis.cancel();},[]);
 function speak(text:string){if(!('speechSynthesis' in window)){setNotice('当前浏览器不支持朗读。');return;}speechSynthesis.cancel();const voice=new SpeechSynthesisUtterance(text);voice.lang='zh-CN';voice.rate=1;voice.volume=voiceVolume;voice.onerror=()=>setNotice('未能朗读，请阅读文字记录。');speechSynthesis.speak(voice);}
 return <aside className="moon-expedition" role="dialog" aria-label="月面地图与基地系统"><header><div><small>EXPEDITION / 月面远征</small><h2>地图与基地系统</h2></div><button aria-label="关闭月面地图" onClick={onClose}>×</button></header><p>可探索区域 700 × 700 m · 调查记录 {discoveries.length} / 3</p>
 <svg className="moon-map" viewBox="0 0 740 740" role="img" aria-label="月面地图，显示基地、三处探索点及你的位置"><rect x="20" y="20" width="700" height="700" rx="12" fill="#111f2b" stroke="#405a70"/>{[120,220,320,420,520,620].map(n=><g key={n} stroke="#263949"><path d={`M${n} 20V720 M20 ${n}H720`}/></g>)}<text x="370" y="52" textAnchor="middle" fill="#a3c6dc">N / 北</text>{fieldRoutes.map((route,i)=><polyline key={i} points={route.map(([x,z])=>`${x+370},${z+370}`).join(' ')} fill="none" stroke="#658a9e" strokeWidth="3" strokeDasharray="8 6"/>)}<circle cx="615" cy="165" r="29" fill="none" stroke="#8c9dab" strokeWidth="8"/><rect x="345" y="343" width="50" height="54" rx="5" fill="#b0c7d4"/><text x="370" y="445" textAnchor="middle" fill="#dce8ef">静海基地</text>{fieldSites.map(site=><g key={site.id}><circle cx={site.x+370} cy={site.z+370} r={navTarget===site.id?12:8} fill={discoveries.includes(site.id)?'#8ce1bd':'#b2dcf7'} stroke="#08131d" strokeWidth="3"/><text x={site.x+370} y={site.z+345} textAnchor="middle" fill="#dce8ef" fontSize="24">{site.name}</text></g>)}<circle cx={playerX+370} cy={playerZ+370} r="9" fill="#fff" stroke="#69d4ff" strokeWidth="4"/></svg>
 <div className="moon-map-shortcuts"><button onClick={()=>onNavigate('base')}>导航回基地</button><button onClick={()=>onNavigate('mission')}>跟随主线任务</button></div><p className="moon-map-note">蓝白圆点代表你的位置。虚线为平整通行走廊，沿途有引导灯。导航只标记目标，不会自动驾驶。</p>
 <div className="moon-field-list">{fieldSites.map(site=><article key={site.id}><header><b>{discoveries.includes(site.id)?'✓ ':''}{site.name}</b><button onClick={()=>onNavigate(site.id)}>{navTarget===site.id?'导航中':'设为目标'}</button></header>{discoveries.includes(site.id)?<details><summary>阅读调查记录</summary><p>{site.report}</p><button onClick={()=>speak(site.report)}>朗读记录</button></details>:<p>{site.id==='sample-station'?'现场任务：检查三条支路，隔离短路加热器并恢复记录器。':site.id==='lost-lander'?'现场任务：隔离破损电池，以正确顺序恢复飞行记录。':'现场任务：调节观测镜方位和仰角，锁定坑壁反射区域。'} 在终端旁下车，面向终端按 E 操作。</p>}</article>)}</div>{discoveries.length===3&&<p className="moon-award">月面勘探员 · 三处远征调查全部完成</p>}
 <section className="moon-power"><h3>基地电力分配</h3><p>{solarRepaired?'主回路 100 单位。科研优先加快现场调查，生态优先增强温室照明；通信供电至少需要 20 单位。':'恢复太阳能主回路后解锁。'}</p><div className="moon-power-options">{(Object.keys(powerProfiles) as PowerMode[]).map(mode=><button key={mode} disabled={!solarRepaired} aria-pressed={powerMode===mode} onClick={()=>onPower(mode)}>{powerProfiles[mode].name}</button>)}</div><div className="moon-power-readings"><span>科研 {powerProfiles[powerMode].research}</span><span>生态 {powerProfiles[powerMode].ecology}</span><span>通信 {powerProfiles[powerMode].comms}</span></div></section>
 {complete&&<section className="moon-launch-entry"><h3>返回飞船</h3><p>步行到飞船旁，可以启动起飞演出。演出结束后可继续探索。</p><button onClick={onLaunch}>启动起飞演出</button></section>}{notice&&<p role="status">{notice}</p>}
 </aside>;
}
