import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {batchMoonStatics} from './moon-batching';
export class CockpitView{
 readonly ready:Promise<void>;private renderer:T.WebGLRenderer;private scene=new T.Scene();private camera=new T.PerspectiveCamera(68,1,.035,1600);private controls:OrbitControls;private observer:ResizeObserver;private dead=false;private seated=true;private yaw=0;private pitch=-.1;private pointer:{x:number;y:number}|null=null;private signal=new AbortController();
 constructor(private host:HTMLElement){
 this.renderer=new T.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;host.appendChild(this.renderer.domElement);this.scene.background=new T.Color('#010204');
 this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enablePan=false;this.controls.minDistance=.4;this.controls.maxDistance=2;this.controls.enabled=false;
 const env=new RoomEnvironment(),pm=new T.PMREMGenerator(this.renderer);this.scene.environment=pm.fromScene(env,.04).texture;this.scene.environmentIntensity=.18;env.dispose();pm.dispose();this.scene.add(new T.HemisphereLight(0x99b5cf,0x101319,.22));
 const sun=new T.DirectionalLight(0xfff1da,3);sun.position.set(-8,12,9);sun.castShadow=true;Object.assign(sun.shadow.camera,{left:-6,right:6,top:6,bottom:-6,near:.1,far:40});sun.shadow.mapSize.set(2048,2048);sun.shadow.bias=-.0002;this.scene.add(sun);
 for(const [x,y,z,c,p] of [[-1.3,2.25,-.2,0xffdfb4,4],[1.3,2.25,-.2,0xffdfb4,4],[0,1.25,1.1,0x5cc9ff,1.3]]){const l=new T.PointLight(c,p,5,2);l.position.set(x,y,z);this.scene.add(l);}
 const resize=()=>{const w=host.clientWidth,h=Math.max(1,host.clientHeight);this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();};this.observer=new ResizeObserver(resize);this.observer.observe(host);resize();
 const canvas=this.renderer.domElement;canvas.style.touchAction='none';const options={signal:this.signal.signal};canvas.addEventListener('pointerdown',e=>{if(this.seated){this.pointer={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}},options);canvas.addEventListener('pointermove',e=>{if(!this.pointer||!this.seated)return;this.yaw-=(e.clientX-this.pointer.x)*.004;this.pitch=T.MathUtils.clamp(this.pitch-(e.clientY-this.pointer.y)*.004,-1.1,1.1);this.pointer={x:e.clientX,y:e.clientY};this.pose();},options);canvas.addEventListener('pointerup',()=>{this.pointer=null;},options);canvas.addEventListener('pointercancel',()=>{this.pointer=null;},options);canvas.addEventListener('wheel',e=>{if(!this.seated)return;e.preventDefault();this.camera.fov=T.MathUtils.clamp(this.camera.fov+e.deltaY*.025,38,90);this.camera.updateProjectionMatrix();},{...options,passive:false});this.view(true);
 this.ready=this.load();this.renderer.setAnimationLoop(()=>{if(!this.dead&&!document.hidden){if(!this.seated)this.controls.update();this.renderer.render(this.scene,this.camera);}});
 }
 private async load(){const model=await new GLTFLoader().loadAsync('/moon/content/cockpit.glb');if(this.dead){this.release(model.scene);return;}model.scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=!o.userData.glazing;o.receiveShadow=!o.userData.glazing;}});batchMoonStatics(model.scene);this.scene.add(model.scene);
 const loader=new T.TextureLoader();const ground=await loader.loadAsync('/moon/content/textures/moon_diffuse.jpg');if(this.dead){ground.dispose();return;}ground.colorSpace=T.SRGBColorSpace;ground.wrapS=ground.wrapT=T.RepeatWrapping;ground.repeat.set(40,40);
 const geometry=new T.PlaneGeometry(900,900,150,150);geometry.rotateX(-Math.PI/2);const pos=geometry.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),r=Math.hypot(x,z);pos.setY(i,-4+T.MathUtils.smoothstep(r,20,180)*(12+8*Math.sin(x*.03)*Math.cos(z*.02)));}geometry.computeVertexNormals();const surface=new T.Mesh(geometry,new T.MeshStandardMaterial({map:ground,color:0x90979c,roughness:1}));surface.receiveShadow=true;this.scene.add(surface);
 const earthTex=await loader.loadAsync('/moon/content/textures/earth.jpg');if(this.dead){earthTex.dispose();return;}earthTex.colorSpace=T.SRGBColorSpace;const earth=new T.Mesh(new T.SphereGeometry(17,48,32),new T.MeshStandardMaterial({map:earthTex,roughness:1,emissive:0x293c59,emissiveIntensity:.3}));earth.position.set(-120,90,360);this.scene.add(earth);
 }
 private pose(){this.camera.rotation.order='YXZ';this.camera.rotation.set(this.pitch,Math.PI+this.yaw,0);}
 view(seat:boolean){this.seated=seat;this.pointer=null;this.controls.enabled=!seat;this.camera.fov=seat?68:75;this.camera.updateProjectionMatrix();if(seat){this.camera.position.set(0,1.53,-.45);this.yaw=0;this.pitch=-.10;this.pose();}else{this.camera.position.set(-1.25,1.76,-1.32);this.controls.target.set(0,1.05,.5);this.controls.update();}}
 private release(root:T.Object3D){const textures=new Set<T.Texture>(),materials=new Set<T.Material>();root.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);for(const v of Object.values(m))if(v instanceof T.Texture)textures.add(v);}}});materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());}
 dispose(){if(this.dead)return;this.dead=true;this.signal.abort();this.observer.disconnect();this.controls.dispose();this.renderer.setAnimationLoop(null);this.release(this.scene);this.scene.environment?.dispose();this.scene.traverse(o=>{if(o instanceof T.DirectionalLight||o instanceof T.PointLight)o.shadow.dispose();});this.renderer.dispose();this.renderer.domElement.remove();}
}

