'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Radio,Maximize2,Compass,X,Send} from 'lucide-react';
import type {MoonWorld} from './moon-world';
import {objective,missionStep,missions,inventory,restoreMission,serializeMission,type MoonState,type MoonAction} from './moon-mission';
import './moon.css';
import {MoonAudio} from './moon-audio';
import {defaultSettings,readSettings} from './moon-settings';
import {SettingsPanel} from './moon-settings-panel';
import {FieldTerminal} from './moon-field-terminal';
import {ExpeditionPanel} from './moon-expedition-panel';
import type {FieldSiteId,NavTarget} from './moon-exploration';
import type {PowerMode} from './moon-systems';
const SAVE_KEY='selene-revival-v1';
const initial:MoonState={carrying:false,powered:false,doorOpen:false,complete:false};
export default function MoonPage(){
 const host=useRef<HTMLDivElement>(null),world=useRef<MoonWorld|null>(null),inflight=useRef<AbortController|null>(null);
 const audio=useRef<MoonAudio|null>(null);const [audioReady,setAudioReady]=useState(false);const [settings,setSettings]=useState(defaultSettings),settingsRef=useRef(settings);settingsRef.current=settings;
 const [settingsOpen,setSettingsOpen]=useState(false),[fieldChallenge,setFieldChallenge]=useState<FieldSiteId|null>(null),[guide,setGuide]=useState(true),[hasDriven,setHasDriven]=useState(false);
 const [mapOpen,setMapOpen]=useState(false);
 const [restartPrompt,setRestartPrompt]=useState(false);
 const [challenge,setChallenge]=useState<'repair'|'link'|null>(null),[tuning,setTuning]=useState(0);
 const [journal,setJournal]=useState(false),[endingDismissed,setEndingDismissed]=useState(false),[saveStatus,setSaveStatus]=useState('自动存档准备中');
 const [connection,setConnection]=useState<'checking'|'available'|'unconfigured'|'offline'>('checking');
 const [loading,setLoading]=useState('正在载入月面地形与基地设施…');
 const [ready,setReady]=useState(false),[error,setError]=useState(''),[s,setS]=useState({...initial,objective:objective(initial),hint:'',distance:0,mode:'overview',locked:false,driving:false,speed:0,discoveries:[] as FieldSiteId[],navTarget:'mission' as NavTarget,navLabel:'当前主线目标',navDistance:0,playerX:0,playerZ:13,bearing:0,surveyProgress:-1,powerMode:'balanced' as PowerMode,flightSeconds:0}),[message,setMessage]=useState(''),[chat,setChat]=useState(false),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[reply,setReply]=useState('这里是基地通讯。可查看任务或呼叫月球车。');
 useEffect(()=>{let live=true;audio.current=new MoonAudio();try{const prefs=readSettings(JSON.parse(localStorage.getItem('selene-settings-v1')??'null'));setSettings(prefs);settingsRef.current=prefs;audio.current.configure(prefs.volume,prefs.muted);setGuide(localStorage.getItem('selene-guide-v1')!=='hidden');}catch{}import('./moon-world').then(({MoonWorld})=>{if(!live||!host.current)return;const w=new MoonWorld(host.current,{audio:f=>audio.current?.update(f),fieldChallenge:id=>{if(live){setFieldChallenge(id);setChat(false);setMapOpen(false);setJournal(false);world.current?.setControlsPaused(true);if(document.pointerLockElement)document.exitPointerLock();}},challenge:a=>{if(live){inflight.current?.abort();setChat(false);setJournal(false);setTuning(a==='repair'?36:90);setChallenge(a);world.current?.setControlsPaused(true);if(document.pointerLockElement)document.exitPointerLock();}},displayError:t=>{if(live){inflight.current?.abort();setError(t);setChat(false);}},progress:(loaded,total)=>{if(live)setLoading(`正在载入基地资源 ${loaded} / ${total}…`);},update:v=>{if(live)setS(v);},message:t=>{if(live){setMessage(t);audio.current?.cue();}}});world.current=w;void w.ready.then(()=>{if(live){try{w.state=restoreMission(JSON.parse(localStorage.getItem(SAVE_KEY)??'null'));w.restoreSession();w.prepareArrival();setSaveStatus('任务、位置和车辆自动保存在此浏览器');}catch{setSaveStatus('浏览器存档不可用，本次进度仅在当前页面保留');}w.applySettings(settingsRef.current);setReady(true);}}).catch(()=>{w.dispose();if(live)setError('场景资源加载失败，请刷新重试。');});}).catch(()=>{if(live)setError('当前浏览器未能启动 3D 场景。');});return()=>{live=false;inflight.current?.abort();world.current?.dispose();audio.current?.dispose();audio.current=null;};},[]);
 useEffect(()=>{audio.current?.configure(settings.volume,settings.muted);if(ready)world.current?.applySettings(settings);try{localStorage.setItem('selene-settings-v1',JSON.stringify(settings));}catch{}},[settings,ready]);
 useEffect(()=>{const pause=()=>audio.current?.pause(true);window.addEventListener('blur',pause);document.addEventListener('visibilitychange',pause);return()=>{window.removeEventListener('blur',pause);document.removeEventListener('visibilitychange',pause);};},[]);
 useEffect(()=>{if(s.driving)setHasDriven(true);},[s.driving]);
 useEffect(()=>{if(ready&&missionStep(s)>1)audio.current?.cue(true);},[s.powered,s.carrying,s.doorOpen,s.solarRepaired,s.complete]);
 useEffect(()=>{world.current?.setAssistantActivity(chat,busy);},[chat,busy,ready]);
 const hideGuide=()=>{setGuide(false);try{localStorage.setItem('selene-guide-v1','hidden');}catch{}};
 const openSettings=()=>{if(!ready||s.mode==='flight'||challenge||fieldChallenge)return;setChat(false);setJournal(false);setMapOpen(false);inflight.current?.abort();setSettingsOpen(true);world.current?.setControlsPaused(true);if(document.pointerLockElement)document.exitPointerLock();};
 const closeSettings=()=>{setSettingsOpen(false);world.current?.setControlsPaused(false);};
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(SAVE_KEY,serializeMission(world.current?.state??s));}catch{setSaveStatus('无法写入存档，请勿关闭页面');}},[ready,s.carrying,s.powered,s.doorOpen,s.diagnosed,s.fuseCarrying,s.solarRepaired,s.sampleCollected,s.sampleDelivered,s.waterOnline,s.commsOnline,s.complete]);
 useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),4500);return()=>clearTimeout(t);},[message]);
 useEffect(()=>{if(ready&&s.complete&&!endingDismissed){world.current?.setControlsPaused(true);if(document.pointerLockElement)document.exitPointerLock();}},[ready,s.complete,endingDismissed]);
 const openMap=()=>{if(!ready||s.mode==='flight'||challenge)return;setChat(false);setJournal(false);inflight.current?.abort();setMapOpen(true);world.current?.setControlsPaused(true);if(document.pointerLockElement)document.exitPointerLock();};
 const closeMap=()=>{setMapOpen(false);world.current?.setControlsPaused(false);};
 const launch=()=>{setMapOpen(false);setChat(false);setJournal(false);setEndingDismissed(true);world.current?.setControlsPaused(false);world.current?.startLaunch();};
 const openChat=()=>{if(!ready||challenge||s.mode==='flight'||s.complete&&!endingDismissed)return;setMapOpen(false);setJournal(false);world.current?.setControlsPaused(true);if(document.pointerLockElement)document.exitPointerLock();setChat(true);};
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(settingsOpen||fieldChallenge){if(e.code==='Escape'){setSettingsOpen(false);setFieldChallenge(null);world.current?.setControlsPaused(false);}return;}if(e.code==='Escape'&&mapOpen){closeMap();return;}if(e.code==='KeyM'&&!e.repeat&&!(e.target as HTMLElement)?.closest('input,textarea')){e.preventDefault();if(mapOpen)closeMap();else openMap();return;}if(e.code==='Escape'&&challenge){setChallenge(null);world.current?.setControlsPaused(false);return;}if(e.code==='Escape'&&journal){setJournal(false);world.current?.setControlsPaused(false);return;}if(e.code==='Escape'&&chat){e.preventDefault();closeChat();return;}if(!e.repeat&&e.code==='KeyC'&&!(e.target as HTMLElement)?.closest('input,textarea')){e.preventDefault();openChat();}};document.addEventListener('keydown',fn);return()=>document.removeEventListener('keydown',fn);},[ready,chat,journal,challenge,mapOpen,s.mode,settingsOpen,fieldChallenge]);
 useEffect(()=>{if(!chat)return;const controller=new AbortController();let live=true;setConnection('checking');const timer=setTimeout(()=>controller.abort(),6000);
 void fetch('/moon/api/command',{signal:controller.signal,cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();const data=await r.json() as {configured?:boolean};if(live)setConnection(data.configured===true?'available':'unconfigured');}).catch(()=>{if(live)setConnection('offline');}).finally(()=>clearTimeout(timer));
 return()=>{live=false;clearTimeout(timer);controller.abort();};},[chat]);
 const closeChat=()=>{inflight.current?.abort();world.current?.setControlsPaused(false);setChat(false);};
 async function send(){if(!ready||!input.trim()||busy||!world.current||connection!=='available')return;const text=input.trim();setInput('');const quick:Record<string,MoonAction>={'查看任务':'status','呼叫月球车':'recall','基地全景':'overview'};if(quick[text]){setReply(world.current.action(quick[text]));return;}const c=new AbortController();inflight.current=c;setBusy(true);setReply('正在连接基地通讯…');const timer=setTimeout(()=>c.abort(),30000);try{const response=await fetch('/moon/api/command',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scene:'moon',text,state:world.current.state}),signal:c.signal});const result=await response.json() as {action?:string;reply?:string;error?:string};if(!response.ok)throw Error(result.error??'通讯失败');if(c.signal.aborted)return;if(result.action==='none')setReply(result.reply??'请明确你的指令。');else if(['status','recall','overview','walk','navigate_base','navigate_station','navigate_lander','navigate_crater','navigate_mission','power_balanced','power_research','power_ecology',...missions.map(m=>m.action)].includes(result.action??''))setReply(world.current.action(result.action as MoonAction));else throw Error('收到无法执行的指令。');}catch(e){if(!c.signal.aborted)setReply((e as Error).message);else setReply('通讯已取消或超时，未执行动作。');}finally{clearTimeout(timer);inflight.current=null;setBusy(false);}}
 return <main onPointerDownCapture={()=>{void audio.current?.unlock().then(ok=>setAudioReady(!!ok));}} onKeyDownCapture={()=>{void audio.current?.unlock().then(ok=>setAudioReady(!!ok));}} className={'moon-app'+(s.mode==='flight'?' is-flight':'')}><div ref={host} className="moon-scene"/><header className="moon-top"><div className="moon-brand"><span className="moon-emblem">S</span><span>SELENE<small>LUNAR OUTPOST / 01</small></span></div><div className="moon-systems"><i className={s.powered?'online':''}/>{s.solarRepaired?'主电源在线':s.powered?'应急供电':'备用电源 · 气闸离线'}<button onClick={openSettings} disabled={!ready||s.mode==='flight'}>设置</button><button aria-label="全屏" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>setMessage('当前窗口不支持全屏。'));}}><Maximize2 size={18}/></button></div></header>
 {ready&&s.mode==='overview'&&<section className="moon-intro"><p className="moon-kicker">FIRST LIGHT / 第一束光</p><h1>静海前哨<span>。</span></h1><p className="moon-description">{s.complete?<>基地已恢复运行。<br/>继续探索生活舱与月面设施。</>:<>地球在远处。你的第一项任务，<br/>是让这座基地重新亮起来。</>}</p><button className="moon-start" onClick={()=>world.current?.walk()}>踏上月面 <ArrowUpRight size={20}/></button><small>也可拖动旋转 · 滚轮缩放，先看看基地</small></section>}
 {ready&&s.mode==='walk'&&<>{!s.driving&&<div className="moon-reticle">+</div>}{s.hint&&!settingsOpen&&!fieldChallenge&&!challenge&&!mapOpen&&!journal&&!chat&&<button className="moon-interact" onClick={()=>world.current?.interact()}><kbd>E</kbd>{s.hint}</button>}</>}
 {ready&&settingsOpen&&<SettingsPanel onPreview={()=>audio.current?.preview()??Promise.resolve('声音尚未准备好，请稍后重试。')} audioReady={audioReady} value={settings} onChange={setSettings} onClose={closeSettings} onHelp={()=>{setGuide(true);try{localStorage.removeItem('selene-guide-v1');}catch{}closeSettings();}} onRecover={()=>{world.current?.recover();closeSettings();}}/>}
 {ready&&fieldChallenge&&<FieldTerminal key={fieldChallenge} siteId={fieldChallenge} onClose={()=>{setFieldChallenge(null);world.current?.setControlsPaused(false);}} onSubmit={answer=>{const done=world.current?.completeFieldChallenge(fieldChallenge,answer)??false;if(done){setFieldChallenge(null);world.current?.setControlsPaused(false);}return done;}}/>}
 {ready&&guide&&s.mode==='walk'&&!settingsOpen&&!fieldChallenge&&!mapOpen&&!journal&&!chat&&!challenge&&<aside className="moon-guide"><button aria-label="隐藏操作引导" onClick={hideGuide}>×</button><small>第一次月面行动</small><b>{s.driving?'驾驶与停车':!s.carrying&&!s.powered?'前往基地补给箱':!s.doorOpen?'让基地重新亮起来':!hasDriven?'准备第一次远征':'探索三处异常地点'}</b><p>{s.driving?'W/S 前进倒车，A/D 可持续转向。松开油门减速，空格刹车，停稳后 E 下车。':!s.carrying&&!s.powered?'点击画面转动视角，WASD 行走。跟随目标距离找到补给箱，靠近并面向它，按 E 取物。':!s.doorOpen?'任务框会显示下一个设备与距离。拿到能源后接通电源，再打开气闸。':!hasDriven?'月球车停在气闸旁。靠近驾驶位按 E 上车，按 M 打开地图，选择远端调查点。':'沿引导灯驶向目标，停车下车后在终端完成现场操作。调查记录会保存在地图中。'}</p></aside>}
 {ready&&s.mode==='walk'&&<div className="moon-navigation"><span>{s.navLabel}</span><b>{s.navDistance} m</b><small>方位 {s.bearing}° · M 地图</small>{Math.max(Math.abs(s.playerX),Math.abs(s.playerZ))>325&&<em>即将到达本次勘探区域边界，请沿原路返回。</em>}</div>}
 {ready&&s.surveyProgress>=0&&<div className="moon-survey"><span>正在下载调查记录 {s.surveyProgress}%</span><progress max={100} value={s.surveyProgress}/><small>请留在终端附近 · E 取消</small></div>}
 {ready&&mapOpen&&<ExpeditionPanel voiceVolume={settings.muted?0:settings.volume} discoveries={s.discoveries} playerX={s.playerX} playerZ={s.playerZ} navTarget={s.navTarget} powerMode={s.powerMode} solarRepaired={!!s.solarRepaired} complete={s.complete} onNavigate={target=>{world.current?.setNavigation(target);closeMap();}} onPower={mode=>world.current?.setPowerMode(mode)} onLaunch={launch} onClose={closeMap}/>}
 {ready&&s.mode==='flight'&&<section className="moon-flight-hud"><p>{s.flightSeconds<3?'点火倒计时 '+Math.max(1,3-Math.floor(s.flightSeconds)):'SELENE / 离开月面'}</p><button onClick={()=>world.current?.finishLaunch()}>结束演出，返回基地</button></section>}
 {ready&&s.driving&&<section className="moon-driving"><span>LUNAR ROVER / 驾驶中</span><strong>{s.speed}<small> km/h</small></strong><p>松开油门减速 · 停稳后按 E 下车</p></section>}
 {ready&&<section className="moon-objective"><span>{s.complete?'MISSION COMPLETE':'当前任务'} <b>{String(missionStep(s)).padStart(2,'0')} / {missions.length}</b></span><h2>{s.objective}</h2><p>{inventory(s)}{!s.complete&&<em>{s.distance} m</em>}</p></section>}
 {ready&&<nav className="moon-actions"><a href="/moon/cockpit/" style={{padding:"10px 14px",color:"#badce8",background:"#10232de6",border:"1px solid #3f5968",borderRadius:6}}>驾驶舱</a><button onClick={openMap}>月面地图 <kbd>M</kbd></button><button onClick={()=>{setMapOpen(false);setChat(false);inflight.current?.abort();setJournal(true);world.current?.setControlsPaused(true);if(document.pointerLockElement)document.exitPointerLock();}}>任务日志</button><button onClick={()=>world.current?.overview()}><Compass size={17}/>基地全景</button><button onClick={openChat}><Radio size={17}/>通讯 <kbd>C</kbd></button></nav>}
 <div className="moon-help">{s.driving?'W/S 前进倒车　 A/D 转向　 空格 刹车　 E 下车　 滚轮 调整跟车距离':s.mode==='walk'?'WASD 行走　 滚轮变焦　 SHIFT 加速　 E 交互　 ESC 释放鼠标':'月面基地 · 全景观察'}</div>{message&&<div className="moon-toast" role="status">{message}</div>}
 {chat&&<aside className="moon-comms"><header><span><Radio size={18}/>基地通讯 / {connection==='available'?'AI':'本地'}</span><button aria-label="关闭通讯" onClick={closeChat}><X size={18}/></button></header><small role="status">{connection==='checking'?'正在检查通讯连接…':connection==='available'?'通讯已连接，可输入自然语言指令。':connection==='unconfigured'?'自由对话暂未启用，可使用下方快捷操作。':'暂时无法连接通讯服务，快捷操作仍可使用。'}</small><p role="status">{reply}</p><div className="moon-quick">{(['status','recall'] as MoonAction[]).map((a,i)=><button key={a} disabled={busy||!ready} onClick={()=>setReply(world.current?.action(a)??'场景尚未就绪')}>{['查看任务','呼叫月球车'][i]}</button>)}</div><form onSubmit={e=>{e.preventDefault();void send();}}><input autoFocus maxLength={500} value={input} onChange={e=>setInput(e.target.value)} placeholder={connection==='available'?'输入通讯指令…':'通讯未连接'} aria-label="通讯指令" disabled={busy||connection!=='available'}/><button disabled={busy||connection!=='available'||!input.trim()} aria-label="发送"><Send size={18}/></button></form><small>取物、安装和开门需要先靠近目标。</small></aside>}


 {ready&&challenge&&<section className="moon-calibration" role="dialog" aria-modal="true" aria-label={challenge==='repair'?'太阳能接线终端':'地球通信终端'}><div><button className="moon-calibration-close" aria-label="关闭校准终端" onClick={()=>{setChallenge(null);world.current?.setControlsPaused(false);}}>×</button><p>FIELD TERMINAL / 现场终端</p><h2>{challenge==='repair'?'主电源回路校准':'地球链路调谐'}</h2><p>{challenge==='repair'?'备用保险模块已就位。将输出电压调至 48 V，然后接通主回路。':'根据科研舱提供的配置，将链路频道调至 132。信号稳定后建立通信。'}</p><output>{tuning}{challenge==='repair'?' V':' CH'}</output><label htmlFor="moon-tuning">{challenge==='repair'?'输出电压':'通信频道'}<input id="moon-tuning" type="range" min={challenge==='repair'?36:90} max={challenge==='repair'?60:170} step={1} value={tuning} onChange={e=>setTuning(Number(e.target.value))}/></label><p>{Math.abs(tuning-(challenge==='repair'?48:132))<=(challenge==='repair'?.5:2)?'校准范围正常，可以连接。':'调整滑块，使读数接近目标值。'}</p><button className="moon-calibration-submit" disabled={Math.abs(tuning-(challenge==='repair'?48:132))>(challenge==='repair'?.5:2)} onClick={()=>{world.current?.action(challenge,tuning);setChallenge(null);world.current?.setControlsPaused(false);}}>{challenge==='repair'?'接通主电源':'建立地球链路'}</button></div></section>}
 {ready&&journal&&<aside className="moon-journal"><header><h2>基地复苏 / 任务日志</h2><button aria-label="关闭任务日志" onClick={()=>{setJournal(false);world.current?.setControlsPaused(false);}}>×</button></header><p>{saveStatus}</p><div className="moon-system-grid"><span>主电源：{s.solarRepaired?'在线':s.powered?'应急供电':'离线'}</span><span>生态支持：{s.waterOnline?'在线':'离线'}</span><span>地球通信：{s.commsOnline?'在线':'离线'}</span><span>携带物：{inventory(s)}</span></div><ol>{missions.map((m,i)=><li key={m.action} className={s.complete||i<missionStep(s)-1?'done':i===missionStep(s)-1?'active':''}><b>{s.complete||i<missionStep(s)-1?'✓ ':''}{m.title}</b>{(s.complete||i<missionStep(s)-1)&&<p>{m.report}</p>}</li>)}</ol><div className="moon-restart">{restartPrompt?<><p>重新开始会清除这个浏览器里的本次任务进度。</p><button onClick={()=>{if(world.current){world.current.restart();}setEndingDismissed(false);setRestartPrompt(false);setJournal(false);setChallenge(null);world.current?.setControlsPaused(false);try{localStorage.setItem(SAVE_KEY,serializeMission(initial));}catch{setSaveStatus('无法写入存档');}}}>确认重新开始</button><button onClick={()=>setRestartPrompt(false)}>保留进度</button></>:<button onClick={()=>setRestartPrompt(true)}>重新开始任务</button>}</div></aside>}
 {ready&&s.complete&&!endingDismissed&&<section className="moon-ending"><p>MISSION COMPLETE / 基地复苏</p><h1>静海前哨，重新上线。</h1><p>你恢复了主电源、温室供水和地球通信。<br/>飞船已收到完整报告，这里再次成为人类的前哨。</p><button onClick={()=>{setEndingDismissed(true);world.current?.setControlsPaused(false);}}>继续探索月面</button><button onClick={launch}>观看飞船起飞</button><small>{saveStatus}</small></section>}
 {(!ready||error)&&<div className="moon-loading" role="status"><span>SELENE</span><p>{error||loading}</p>{error&&<button onClick={()=>location.reload()}>重新加载</button>}</div>}
 </main>;
}
