import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {GTAOPass} from 'three/addons/postprocessing/GTAOPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {RectAreaLightUniformsLib} from 'three/addons/lights/RectAreaLightUniformsLib.js';
import {batchMoonStatics} from './moon-batching';
export class CockpitView{
 readonly ready:Promise<void>;private renderer:T.WebGLRenderer;private scene=new T.Scene();private camera=new T.PerspectiveCamera(64,1,.035,1600);private controls:OrbitControls;private observer:ResizeObserver;private dead=false;private seated=true;private yaw=0;private pitch=-.1;private pointer:{x:number;y:number}|null=null;private signal=new AbortController();
 private composer:EffectComposer;private ao:GTAOPass;private bloom:UnrealBloomPass;private output:OutputPass;private opticalSurfaces:T.Object3D[]=[];private dirty=true;
 constructor(private host:HTMLElement){
 this.renderer=new T.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.10;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;host.appendChild(this.renderer.domElement);this.scene.background=new T.Color('#010204');
 this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enablePan=false;this.controls.minDistance=.4;this.controls.maxDistance=1.8;this.controls.minPolarAngle=.3;this.controls.maxPolarAngle=1.83;this.controls.enabled=false;
 const env=new RoomEnvironment(),pm=new T.PMREMGenerator(this.renderer);this.scene.environment=pm.fromScene(env,.08).texture;this.scene.environmentIntensity=.12;env.dispose();pm.dispose();this.scene.add(new T.HemisphereLight(0xc2d4e5,0x303942,.08));
 const sun=new T.DirectionalLight(0xeaf1ff,2.2);sun.position.set(-8,12,9);sun.castShadow=true;Object.assign(sun.shadow.camera,{left:-3.5,right:3.5,top:3.5,bottom:-3.5,near:.1,far:40});sun.shadow.mapSize.set(2048,2048);sun.shadow.bias=-.00008;sun.shadow.normalBias=.006;this.scene.add(sun);
 RectAreaLightUniformsLib.init();
 const area=(color:number,intensity:number,w:number,h:number,position:T.Vector3,target:T.Vector3)=>{const l=new T.RectAreaLight(color,intensity,w,h);l.position.copy(position);l.lookAt(target);this.scene.add(l);};
 area(0xffdfb6,18,.18,2.5,new T.Vector3(-1.39,2.43,-.25),new T.Vector3(0,.7,0));
 area(0xb4d3f4,12,.18,2.5,new T.Vector3(1.39,2.43,-.25),new T.Vector3(0,.7,0));
 area(0x95d5f4,3.2,1.05,.36,new T.Vector3(0,1.12,1.27),new T.Vector3(0,1.05,-.6));
 area(0xffe4cd,6,.8,.1,new T.Vector3(0,2.2,-1.7),new T.Vector3(0,1,0));
 const target=new T.WebGLRenderTarget(1,1,{type:T.HalfFloatType,samples:Math.min(4,this.renderer.capabilities.maxSamples)});
 this.composer=new EffectComposer(this.renderer,target);this.composer.addPass(new RenderPass(this.scene,this.camera));
 this.ao=new GTAOPass(this.scene,this.camera);this.ao.blendIntensity=.85;this.ao.updateGtaoMaterial({radius:.23,thickness:.14,distanceFallOff:.65,scale:1,samples:12,screenSpaceRadius:false});this.ao.updatePdMaterial({radius:5,samples:12});this.ao.setSceneClipBox(new T.Box3(new T.Vector3(-2.15,-.2,-2.1),new T.Vector3(2.15,2.75,2.15)));
 // Transparent glazing and printed legends must not occlude the normal/depth pass.
 const renderAO=this.ao.render.bind(this.ao);this.ao.render=(renderer,write,read,delta,mask)=>{const visible=this.opticalSurfaces.map(o=>o.visible);this.opticalSurfaces.forEach(o=>{o.visible=false;});try{renderAO(renderer,write,read,delta,mask);}finally{this.opticalSurfaces.forEach((o,i)=>{o.visible=visible[i];});}};
 this.composer.addPass(this.ao);this.bloom=new UnrealBloomPass(new T.Vector2(1,1),.12,.25,1.3);this.composer.addPass(this.bloom);this.output=new OutputPass();this.composer.addPass(this.output);
 this.controls.addEventListener('change',()=>{this.dirty=true;});
 const resize=()=>{const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);this.renderer.setSize(w,h);this.composer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.dirty=true;};this.observer=new ResizeObserver(resize);this.observer.observe(host);resize();
 const canvas=this.renderer.domElement;canvas.style.touchAction='none';const options={signal:this.signal.signal};canvas.addEventListener('pointerdown',e=>{if(this.seated){this.pointer={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}},options);canvas.addEventListener('pointermove',e=>{if(!this.pointer||!this.seated)return;this.yaw-=(e.clientX-this.pointer.x)*.004;this.pitch=T.MathUtils.clamp(this.pitch-(e.clientY-this.pointer.y)*.004,-1.1,1.1);this.pointer={x:e.clientX,y:e.clientY};this.pose();},options);canvas.addEventListener('pointerup',()=>{this.pointer=null;},options);canvas.addEventListener('pointercancel',()=>{this.pointer=null;},options);canvas.addEventListener('wheel',e=>{if(!this.seated)return;e.preventDefault();this.camera.fov=T.MathUtils.clamp(this.camera.fov+e.deltaY*.025,38,90);this.camera.updateProjectionMatrix();},{...options,passive:false});this.view(true);
 canvas.addEventListener('wheel',()=>{this.dirty=true;},{signal:this.signal.signal});document.addEventListener('visibilitychange',()=>{this.dirty=true;},{signal:this.signal.signal});
 this.ready=this.load();this.renderer.setAnimationLoop(()=>{if(!this.dead&&!document.hidden){if(!this.seated)this.controls.update();if(this.dirty){this.composer.render();this.dirty=false;}}});
 }
 private async load(){const model=await new GLTFLoader().loadAsync('/moon/content/cockpit.glb');if(this.dead){this.release(model.scene);return;}model.scene.traverse(o=>{if(o instanceof T.Mesh){if(o.userData.surfaceLabel)o.userData.glazing=true;if(o.userData.glazing)this.opticalSurfaces.push(o);o.castShadow=!o.userData.glazing;o.receiveShadow=!o.userData.glazing;for(const material of Array.isArray(o.material)?o.material:[o.material]){if(material instanceof T.MeshStandardMaterial){for(const key of ['map','normalMap','roughnessMap'] as const){const tex=material[key];if(tex)tex.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());}if(o.userData.surfaceLabel){material.depthWrite=false;material.polygonOffset=true;material.polygonOffsetFactor=-1;material.polygonOffsetUnits=-1;}}}}});batchMoonStatics(model.scene);this.scene.add(model.scene);this.dirty=true;
 const loader=new T.TextureLoader();const groundTextures=await Promise.all(['/moon/content/textures/moon_diffuse.jpg','/moon/content/textures/moon_nor_gl.jpg','/moon/content/textures/moon_rough.jpg'].map(path=>loader.loadAsync(path)));if(this.dead){groundTextures.forEach(t=>t.dispose());return;}const [ground,normal,rough]=groundTextures;ground.colorSpace=T.SRGBColorSpace;for(const texture of groundTextures){texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(70,70);texture.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());}
 const geometry=new T.PlaneGeometry(900,900,240,240);geometry.rotateX(-Math.PI/2);const pos=geometry.attributes.position;
 const craters=[[-48,90,27,6],[48,115,32,8],[105,180,48,12],[-132,235,60,15],[8,240,66,14]];
 for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),r=Math.hypot(x,z),fade=T.MathUtils.smoothstep(r,18,65);let y=-4+T.MathUtils.smoothstep(r,40,210)*(11+8*Math.sin(x*.021)*Math.cos(z*.016));y+=fade*(1.2*Math.sin(x*.14+Math.cos(z*.08))*Math.cos(z*.13)+.4*Math.sin(x*.38+z*.19));for(const [cx,cz,radius,depth] of craters){const d=Math.hypot(x-cx,z-cz)/radius;if(d<1.7)y+=fade*depth*(.4*Math.exp(-Math.pow((d-1)/.13,2))-.68*Math.exp(-Math.pow(d/.73,4)));}pos.setY(i,y);}
 geometry.computeVertexNormals();const surface=new T.Mesh(geometry,new T.MeshStandardMaterial({map:ground,normalMap:normal,normalScale:new T.Vector2(.7,.7),roughnessMap:rough,color:0x878d93,roughness:1}));surface.receiveShadow=true;this.scene.add(surface);this.dirty=true;
 const earthTex=await loader.loadAsync('/moon/content/textures/earth.jpg');if(this.dead){earthTex.dispose();return;}earthTex.colorSpace=T.SRGBColorSpace;const earth=new T.Mesh(new T.SphereGeometry(17,48,32),new T.MeshStandardMaterial({map:earthTex,roughness:1,emissive:0x293c59,emissiveIntensity:.3}));earth.position.set(-200,135,420);this.scene.add(earth);this.dirty=true;
 }
 private pose(){this.camera.rotation.order='YXZ';this.camera.rotation.set(this.pitch,Math.PI+this.yaw,0);this.dirty=true;}
 view(seat:boolean){this.seated=seat;this.pointer=null;this.controls.enabled=!seat;this.camera.fov=seat?64:68;this.camera.updateProjectionMatrix();if(seat){this.camera.position.set(0,1.53,-.45);this.yaw=0;this.pitch=-.10;this.pose();}else{this.camera.position.set(-1.25,1.66,-1.05);this.controls.target.set(0,1.1,0);this.controls.update();}this.dirty=true;}
 private release(root:T.Object3D){const textures=new Set<T.Texture>(),materials=new Set<T.Material>();root.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){materials.add(m);for(const v of Object.values(m))if(v instanceof T.Texture)textures.add(v);}}});materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());}
 dispose(){if(this.dead)return;this.dead=true;this.signal.abort();this.observer.disconnect();this.controls.dispose();this.renderer.setAnimationLoop(null);this.ao.dispose();this.bloom.dispose();this.output.dispose();this.composer.dispose();this.release(this.scene);this.scene.environment?.dispose();this.scene.traverse(o=>{if(o instanceof T.DirectionalLight||o instanceof T.PointLight)o.shadow.dispose();});this.renderer.dispose();this.renderer.domElement.remove();}
}
