import React,{useState,type ReactNode} from 'react';
import {Radio,Box,FlaskConical,MapPin,LockKeyhole,Check} from 'lucide-react';
import {FieldArchives} from './moon-field-archives-panel';
import {fieldArchives} from './moon-field-archives';
import {rockSamples,type AdventureState,type AdventureAction} from './moon-adventure';
import {ArchiveReward,Receiver,SignalWave,useTerminalFocus,lunarUiAsset} from './moon-interface';
export function AdventurePanel({state,signal,near,atLab,powered,onAction,onClose,mainContent,initialTab='tasks'}:{state:AdventureState;signal:number;near:string;atLab:boolean;powered:boolean;onAction:(a:AdventureAction)=>boolean;onClose:()=>void;mainContent?:ReactNode;initialTab?:'main'|'tasks'}){
 const ref=useTerminalFocus();
 const [tab,setTab]=useState<'main'|'tasks'|'archives'>(initialTab),[archiveId,setArchiveId]=useState('');
 const [frequency,setFrequency]=useState(140),[answers,setAnswers]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
 const openArchive=(id='')=>{setArchiveId(id);setNotice('');setTab('archives');};
 const act=(a:AdventureAction)=>{if(onAction(a)){setNotice('操作完成，记录已保存。');if(a.kind==='decode')openArchive('distant-echo');else if(a.kind==='study')openArchive(a.id);}else setNotice('操作未完成：请检查位置、供电和鉴定结果。');};
 const signalStep={idle:0,active:1,recovered:2,decoded:3}[state.signal];
 return <section ref={ref} className="moon-mission-terminal moon-instrument" role="dialog" aria-modal="true" aria-label="任务日志"><header className="moon-terminal-header"><div className="moon-terminal-brand">SELENE<small>FIELD TERMINAL</small></div><nav className="moon-archive-tabs" aria-label="任务日志页签"><button aria-pressed={tab==='main'} onClick={()=>setTab('main')}>主线任务</button><button aria-pressed={tab==='tasks'} onClick={()=>setTab('tasks')}>信号与研究</button><button aria-pressed={tab==='archives'} onClick={()=>openArchive()}>档案室 <span>{fieldArchives(state).length}</span></button></nav><button className="moon-terminal-close" data-terminal-close aria-label="关闭任务日志" onClick={onClose}><kbd>Esc</kbd><span>关闭</span></button></header>
 <div key={tab} className={'moon-terminal-body is-'+tab}>{tab==='main'?<div className="moon-journal-content"><div className="moon-terminal-section-title"><small>MISSION / 第一束光</small><h2>让基地重新亮起来。</h2></div>{mainContent}</div>:tab==='archives'?<FieldArchives key={archiveId} state={state} initialId={archiveId}/>:<div className="moon-research-workspace"><section className="moon-signal-mission"><div className="moon-terminal-section-title"><small>SIG—001 / 深空接收</small><h2>未知信号追踪</h2></div><ol className="moon-signal-steps">{['发现异常','回收芯片','基地解码'].map((label,i)=><li key={label} className={i<signalStep?'done':''}>{i<signalStep?<Check size={13}/>:<span/>}{label}</li>)}</ol>
 {state.signal==='idle'?<div className="moon-receiver-idle"><Radio size={35}/><h3>接收器正在监听</h3><SignalWave/><p>在月面继续探索，或使用望远镜寻找线索。西北方向可能有一段尚未解读的信号。</p></div>:state.signal==='active'?<><div className="moon-live-signal"><Radio size={19}/><span>西北区域</span><strong>{signal}<small>%</small></strong></div><p>搜索西北方向，信号越强，距离越近。找到带蓝色指示灯的破损探测器，停车下车后调查。</p>{near==='signal'?<><Receiver value={frequency} min={140} max={145} target={142.4} step={.1} unit="MHz" label="接收频率" onChange={setFrequency}/><p className="moon-instrument-note">机身铭牌：救援信道 142.4 MHz。</p><button className="moon-instrument-action" disabled={Math.abs(frequency-142.4)>.051} onClick={()=>act({kind:'recover',frequency})}><Box size={17}/>回收存储芯片 <span>→</span></button></>:<div className="moon-instrument-note"><MapPin size={16}/>靠近探测器后可打开调谐仪器。</div>}</>:state.signal==='recovered'?<div className="moon-chip-recovered"><Box size={37}/><h3>芯片已封存</h3><p>带回工作室，在分析终端解码。研究区位于气闸主通道尽头左侧。</p><button className="moon-instrument-action" disabled={!atLab||!powered} onClick={()=>act({kind:'decode'})}>解码探测器数据 <span>→</span></button>{(!atLab||!powered)&&<small>{!powered?'分析终端等待供电':'前往工作室分析终端'}</small>}</div>:<><img className="moon-signal-cover" src={lunarUiAsset('archive-distant-echo-v1.png')} alt="遗留探测器档案插画"/><ArchiveReward title="远方的回声" onRead={()=>openArchive('distant-echo')}/><p>重复载波中保存着首批勘探队的采样任务。三处岩样坐标已解读，等待你继续调查。</p></>}
 </section><section className="moon-sample-research"><div className="moon-terminal-section-title"><small>GEO / 月面科学</small><h2>月岩采样与研究 <span>{state.studied.length}<i>/ 3</i></span></h2></div><p className="moon-lab-status">{atLab&&powered?<><FlaskConical size={16}/>研究终端在线</>:<><LockKeyhole size={16}/>{!powered?'完成供电后，可在工作室研究岩样':'研究地点：工作室 · 气闸主通道尽头左侧'}</>}</p>
 {rockSamples.map((r,i)=>{const collected=state.samples.includes(r.id),studied=state.studied.includes(r.id);return <article key={r.id} className={'moon-specimen'+(studied?' is-studied':'')}><header><span className="moon-specimen-number">0{i+1}</span><div><h3>{r.name}</h3><small><MapPin size={12}/> X {r.x} / Z {r.z}</small></div><span className="moon-specimen-state">{studied?'已研究':collected?'已采集':'未采集'}</span></header>{!collected?<><p>寻找浅蓝标牌，靠近岩样后按 E 采集。</p><button disabled={near!==r.id} onClick={()=>act({kind:'collect',id:r.id})}>封装这份岩样 <span>→</span></button></>:studied?<><p>{r.type}：{r.report}</p><button onClick={()=>openArchive(r.id)}>查看研究报告 <span>→</span></button></>:<><p className="moon-specimen-clue">镜检特征：{r.clue}</p><fieldset disabled={!atLab||!powered}><legend>按特征鉴定岩石类型</legend><div className="moon-specimen-choices">{([['basalt','玄武岩'],['breccia','角砾岩'],['anorthosite','斜长岩']] as const).map(([id,label])=><button key={id} aria-pressed={answers[r.id]===id} onClick={()=>setAnswers({...answers,[r.id]:id})}>{label}</button>)}</div></fieldset><button className="moon-instrument-action" disabled={!atLab||!powered||!answers[r.id]} onClick={()=>act({kind:'study',id:r.id,answer:answers[r.id]})}>保存研究结果 <span>→</span></button></>}</article>;})}
 {state.studied.length>0&&<p className="moon-research-upgrade"><Check size={15}/>噪声校准已应用 · 接收范围提升至 220 m</p>}{state.studied.length===3&&<ArchiveReward title="月面地质员" onRead={()=>openArchive('lunar-geologist')}/>}</section></div>}</div>{notice&&<div className="moon-terminal-notice" role="status">{notice}</div>}
 </section>;
}
