import {useState} from 'react';
import {rockSamples,type AdventureState,type AdventureAction} from './moon-adventure';
export function AdventurePanel({state,signal,near,atLab,powered,onAction,onClose}:{state:AdventureState;signal:number;near:string;atLab:boolean;powered:boolean;onAction:(a:AdventureAction)=>boolean;onClose:()=>void}){
 const [frequency,setFrequency]=useState(140),[answers,setAnswers]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
 const act=(a:AdventureAction)=>setNotice(onAction(a)?'已完成，探索记录已更新。':'操作未完成：请检查位置、供电和答案。');
 return <section className="moon-expedition" role="dialog" aria-label="信号与月岩研究"><header><div><small>FIELD SCIENCE / 探索支线</small><h2>信号与月岩研究</h2></div><button onClick={onClose} aria-label="关闭探索支线">×</button></header>
 <h3>未知信号追踪</h3>{state.signal==='idle'?<p>接收器正在监听。继续在月面探索，靠近西北方向的异常区域，或使用望远镜，都可能收到线索。</p>:state.signal==='active'?<><p>收到旧式探测器的求救载波。搜索基地西北方向，信号越强，距离越近。靠近后下车调查带蓝色指示灯的破损探测器。</p><strong>信号强度 {signal}%</strong><progress style={{width:'100%'}} max={100} value={signal}/>{near==='signal'&&<><p>机身铭牌：救援信道 142.4 MHz。将接收频率调到载波中心，提取存储芯片。</p><label>接收频率 {frequency.toFixed(1)} MHz<input aria-label="接收频率" type="range" min="140" max="145" step="0.1" value={frequency} onChange={e=>setFrequency(Number(e.target.value))}/></label><button onClick={()=>act({kind:'recover',frequency})}>锁定载波并回收芯片</button></>}</>:state.signal==='recovered'?<><p>芯片已封存。带回工作室，在分析终端解码。气闸主通道尽头左侧的桌面是研究区。</p><button disabled={!atLab||!powered} onClick={()=>act({kind:'decode'})}>解码探测器数据</button></>:<><p className="moon-award">未知信号追踪完成 · 获得「远方的回声」档案</p><p>探测器一直重复发送首批勘探队的采样任务。它的记录标出了三处有价值的岩样，而非另一支失联队伍。采样坐标已整理在下方。</p></>}
 <h3>月岩采样与研究 · {state.studied.length}/3</h3><p>找到带浅蓝标牌的岩样，靠近按 E 采集。样本独立存放，不占主线能源背包。带回有电的工作室，按纹理特征鉴定。</p>
 {rockSamples.map(r=><article key={r.id} style={{borderTop:'1px solid #456575',padding:'14px 0'}}><b>{r.name} · {state.studied.includes(r.id)?'已研究':state.samples.includes(r.id)?'已采集':'未采集'}</b><p>采样坐标 X {r.x} / Z {r.z}</p>{!state.samples.includes(r.id)?<button disabled={near!==r.id} onClick={()=>act({kind:'collect',id:r.id})}>封装这份岩样</button>:state.studied.includes(r.id)?<p>{r.type}：{r.report}</p>:<><p>镜检特征：{r.clue}</p><select aria-label={r.name+'鉴定'} value={answers[r.id]??''} onChange={e=>setAnswers({...answers,[r.id]:e.target.value})}><option value="">选择岩石类型</option><option value="basalt">玄武岩</option><option value="breccia">角砾岩</option><option value="anorthosite">斜长岩</option></select><button disabled={!atLab||!powered||!answers[r.id]} onClick={()=>act({kind:'study',id:r.id,answer:answers[r.id]})}>提交研究结果</button></>}</article>)}
 {!atLab&&<p>研究地点：工作室 X −1.5 / Z −16.2。先按主线恢复供电并打开气闸。</p>}{atLab&&!powered&&<p>终端未通电，请先恢复基地供电。</p>}{state.studied.length>0&&<p className="moon-award">矿物噪声校准已应用：信号接收范围由 150 m 提升至 220 m。</p>}{state.studied.length===3&&<p className="moon-award">月岩研究完成 · 获得「月面地质员」研究记录</p>}{notice&&<p role="status">{notice}</p>}
 </section>;
}
