import {SprintLatch} from './moon-sprint';
import {MoonHoloDesk} from './moon-holo-desk';
import {MoonCompanion,type CompanionMood} from './moon-companion';
import {solveField} from './moon-field-challenge';
import type {MoonSettings} from './moon-settings';
import type {SoundFrame} from './moon-audio';
import * as T from 'three';
import {readSession,type MoonSession} from './moon-session';
import {EXPLORATION_LIMIT,fieldSites,fieldRoutes,segmentDistance,validDiscoveries,type FieldSiteId,type NavTarget} from './moon-exploration';
import {prepareFlightShip} from './moon-flight';
import {buildFieldSites} from './moon-field-scenes';
import {powerProfiles,surveyDuration,launchAltitude,type PowerMode} from './moon-systems';
import {advanceRover,roverFits} from './moon-driving';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createLunarTerrain,groundHeight} from './moon-terrain';
import {batchMoonStatics} from './moon-batching';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {missionAction,objective,missionTarget,currentMission,missions,initialState,type MoonState,type MoonAction} from './moon-mission';
type Hooks={audio?:(frame:SoundFrame)=>void;fieldChallenge?:(id:FieldSiteId)=>void;challenge?:(action:'repair'|'link')=>void;displayError?:(message:string)=>void;progress?:(loaded:number,total:number)=>void;update:(s:MoonState&{objective:string;hint:string;distance:number;mode:string;locked:boolean;driving:boolean;speed:number;discoveries:FieldSiteId[];navTarget:NavTarget;navLabel:string;navDistance:number;playerX:number;playerZ:number;bearing:number;surveyProgress:number;powerMode:PowerMode;flightSeconds:number})=>void;message:(text:string)=>void};
type Obstacle={id:string;x:number;z:number;hx:number;hz:number};
const interactionPoints=Object.fromEntries(missions.map(m=>[m.action,new T.Vector3(...m.point)]));
const interactionWalls=new Set(['wall','rear-passage','facade','passage-wall','living-wall','living-front','living-back']);
export {groundHeight} from './moon-terrain';
export class MoonWorld{
 readonly ready:Promise<void>;state:MoonState={carrying:false,powered:false,doorOpen:false,complete:false};
 private taskLamps:T.Mesh[]=[];private greenhouseLight:T.PointLight|null=null;
 discoveries:FieldSiteId[]=[];private navTarget:NavTarget='mission';private powerMode:PowerMode='balanced';private surveying:FieldSiteId|null=null;private surveyElapsed=0;private flightShip:T.Group|null=null;private flightSeconds=0;private plume:T.Mesh|null=null;private sunlight:T.DirectionalLight|null=null;
 private sprint=new SprintLatch();private holoDesk:MoonHoloDesk|null=null;private companion:MoonCompanion|null=null;private companionMood:CompanionMood='idle';private assetsReady=false;private lastSessionSave=0;
 private driving=false;private driveSpeed=0;private chaseDistance=8;private driveBlocked=false;
 private sensitivity=1;private controlsPaused=false;private displayLost=false;
 private loadingCleanups=new Set<()=>void>();private walkPose:{position:T.Vector3;yaw:number;pitch:number}|null=null;
 private scene=new T.Scene();private camera=new T.PerspectiveCamera(64,1,.05,10000);private renderer:T.WebGLRenderer;private orbit:OrbitControls;private model?:T.Group;private ids=new Map<string,T.Object3D>();private obstacles:Obstacle[]=[];private keys=new Set<string>();private signal=new AbortController();private frame=0;private last=performance.now();private yaw=0;private pitch=0;private mode='overview';private targetFov=64;private dead=false;private drag=false;private door=0;private updateAt=0;private roofLights:T.PointLight[]=[];private lightingPowered=false;private roverGoal:T.Vector3|null=null;private resizeObserver:ResizeObserver;private env?:T.WebGLRenderTarget;private pmrem?:T.PMREMGenerator;private ring:T.Mesh;
 constructor(private host:HTMLDivElement,private hooks:Hooks){
 this.renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;host.appendChild(this.renderer.domElement);const canvas=this.renderer.domElement;canvas.tabIndex=0;
 this.scene.background=new T.Color('#020407');this.pmrem=new T.PMREMGenerator(this.renderer);const room=new RoomEnvironment();this.env=this.pmrem.fromScene(room,.04);room.dispose();this.scene.environment=this.env.texture;this.scene.environmentIntensity=.32;
 this.scene.add(new T.HemisphereLight(0xd8e0e6,0x15171a,.32));const sun=new T.DirectionalLight(0xfffafa,4.0);sun.position.set(-45,28,35);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);Object.assign(sun.shadow.camera,{left:-48,right:48,top:48,bottom:-48,near:1,far:160});sun.shadow.normalBias=.035;sun.shadow.bias=-.0001;this.scene.add(sun,sun.target);this.sunlight=sun;
 for(const z of [-8,-12,-16,-20,-24,-28,-31]){const l=new T.PointLight(0xffdfbf,0,9,2);l.position.set(0,2.6,z);l.userData.nominalIntensity=z<=-24?12:26;l.castShadow=true;l.shadow.mapSize.set(256,256);l.shadow.camera.near=.1;l.shadow.bias=-.0001;l.shadow.normalBias=.012;l.shadow.autoUpdate=false;l.shadow.needsUpdate=true;this.roofLights.push(l);this.scene.add(l);}
 for(const [x,y,z,power] of [[-3.44,1.64,-25.75,1.8],[3.58,3.2,-22.85,4.5]]){const light=new T.PointLight(0xffe4c7,0,2.4,2);light.position.set(x,y,z);light.userData.nominalIntensity=power;this.roofLights.push(light);this.scene.add(light);}
 this.camera.position.set(47,27,52);this.orbit=new OrbitControls(this.camera,canvas);this.orbit.target.set(0,1,-3);this.orbit.enableDamping=true;this.orbit.maxDistance=100;this.orbit.minDistance=5;this.orbit.maxPolarAngle=Math.PI*.48;this.orbit.update();
 this.ring=new T.Mesh(new T.RingGeometry(.55,.62,48),new T.MeshBasicMaterial({color:0xaddfee,transparent:true,opacity:.65,side:T.DoubleSide}));this.ring.rotation.x=-Math.PI/2;this.scene.add(this.ring);
 const signal=this.signal.signal;document.addEventListener('keydown',e=>{if(this.controlsPaused||(e.target as HTMLElement)?.closest('input,textarea,button'))return;if(this.mode==='walk'&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight','Space'].includes(e.code)){e.preventDefault();this.keys.add(e.code);if(!this.driving&&(e.code==='ShiftLeft'||e.code==='ShiftRight'))this.sprint.press(e.code);}if(e.code==='KeyE'&&!e.repeat&&this.mode==='walk')this.interact();},{signal});document.addEventListener('keyup',e=>{this.keys.delete(e.code);this.sprint.release(e.code);},{signal});window.addEventListener('blur',()=>{this.driveSpeed=0;this.keys.clear();this.sprint.reset();this.drag=false;},{signal});document.addEventListener('pointerlockchange',()=>{this.driveSpeed=0;this.keys.clear();this.sprint.reset();if(document.pointerLockElement===canvas)canvas.focus({preventScroll:true});this.notify();},{signal});
 canvas.addEventListener('wheel',e=>{if(this.controlsPaused||this.mode!=='walk'||e.ctrlKey)return;e.preventDefault();const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?this.host.clientHeight:1);if(this.driving){this.chaseDistance=T.MathUtils.clamp(this.chaseDistance+T.MathUtils.clamp(delta,-240,240)*.015,5,15);return;}this.targetFov=T.MathUtils.clamp(this.targetFov+T.MathUtils.clamp(delta,-240,240)*.04,30,110);},{signal,passive:false});
 canvas.addEventListener('pointerdown',()=>{if(this.controlsPaused)return;this.drag=true;if(this.mode==='walk')this.lock();},{signal});window.addEventListener('pointerup',()=>this.drag=false,{signal});document.addEventListener('mousemove',e=>{if(this.controlsPaused||this.driving||this.mode!=='walk'||document.pointerLockElement!==canvas&&!this.drag)return;this.yaw-=e.movementX*.002*this.sensitivity;this.pitch=T.MathUtils.clamp(this.pitch-e.movementY*.002*this.sensitivity,-1.35,1.35);this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');},{signal});
 document.addEventListener('visibilitychange',()=>this.syncVisibility(),{signal});
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.displayLost=true;this.setControlsPaused(true);this.syncVisibility();if(document.pointerLockElement===canvas)document.exitPointerLock();this.hooks.displayError?.('3D 显示暂时中断，正在等待恢复。也可重新加载，但会重置当前探索进度。');},{signal});
 canvas.addEventListener('webglcontextrestored',()=>this.restoreDisplay(),{signal});
 this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();this.ready=this.load();this.syncVisibility();
 }
 private createEnvironment(){
 const generator=new T.PMREMGenerator(this.renderer),room=new RoomEnvironment();
 try{return {generator,environment:generator.fromScene(room,.04)};}catch(error){generator.dispose();throw error;}finally{room.dispose();}
 }
 private refreshEnvironment(){
 // PMREM generators share resources: dispose the old one before constructing its replacement.
 this.scene.environment=null;this.env?.dispose();this.pmrem?.dispose();this.env=undefined;this.pmrem=undefined;
 const {generator,environment}=this.createEnvironment();this.pmrem=generator;this.env=environment;this.scene.environment=environment.texture;
 }
 private restoreDisplay(){
 if(this.dead||!this.displayLost)return;
 try{
  this.refreshEnvironment();for(const light of this.roofLights)light.shadow.needsUpdate=true;
  this.resize();this.displayLost=false;this.setControlsPaused(false);this.syncVisibility();
  this.hooks.displayError?.('');this.hooks.message('3D 显示已恢复，探索进度已保留。');this.notify();
 }catch{
  this.displayLost=true;this.setControlsPaused(true);this.syncVisibility();this.hooks.displayError?.('暂时无法恢复 3D 显示，请重新加载场景。当前探索进度将重置。');
 }
 }
 private syncVisibility(){this.persistSession();this.driveSpeed=0;this.keys.clear();this.sprint.reset();this.drag=false;cancelAnimationFrame(this.frame);this.frame=0;if(this.dead||this.displayLost||document.hidden)return;this.last=performance.now();this.frame=requestAnimationFrame(this.animate);}
 private own<T>(promise:Promise<T>,release:(value:T)=>void):Promise<T>{return promise.then(value=>{if(this.dead)release(value);else this.loadingCleanups.add(()=>release(value));return value;});}
 private async load(){const manager=new T.LoadingManager();manager.onProgress=(_url,loaded,total)=>{if(!this.dead)this.hooks.progress?.(loaded,total);};const loader=new T.TextureLoader(manager);const modelLoader=new GLTFLoader(manager);
 const [companionAsset,gltf,layout,rock,diff,norm,rough,earth]=await Promise.all([
 this.own(modelLoader.loadAsync('/moon/content/companion.glb'),g=>this.release(g.scene)),
 this.own(modelLoader.loadAsync('/moon/content/base.glb'),g=>this.release(g.scene)),
 fetch('/moon/content/layout.json',{signal:this.signal.signal}).then(r=>{if(!r.ok)throw Error('布局加载失败');return r.json();}),
 this.own(modelLoader.loadAsync('/moon/content/rock/moon_rock_06.gltf'),g=>this.release(g.scene)),
 ...['moon_diffuse.jpg','moon_nor_gl.jpg','moon_rough.jpg','earth.jpg'].map(name=>this.own(loader.loadAsync('/moon/content/textures/'+name),t=>t.dispose()))
 ] as const);
 if(this.dead)return;
 if(!Array.isArray((layout as {colliders?:unknown}|null)?.colliders))throw Error('布局数据无效');
 this.holoDesk=new MoonHoloDesk();this.scene.add(this.holoDesk.root);this.companion=new MoonCompanion(companionAsset.scene);this.scene.add(this.companion.root);
 this.obstacles=(layout as {colliders:Obstacle[]}).colliders;this.model=gltf.scene;
 this.flightShip=prepareFlightShip(gltf.scene);
 gltf.scene.traverse(o=>{if(o.userData.moonId&&o.userData.moonId!=='flight-assembly')this.ids.set(o.userData.moonId,o);if(o instanceof T.Mesh){if(o.userData.moonId==='power-light'&&!Array.isArray(o.material))o.material=o.material.clone();o.castShadow=!o.userData.glazing&&!o.userData.surfaceLabel;o.receiveShadow=!o.userData.glazing;}});for(const [id,object] of this.ids)if(id.startsWith('wheel-'))batchMoonStatics(object as T.Group);const roverRoot=this.ids.get('rover');if(roverRoot)batchMoonStatics(roverRoot as T.Group);batchMoonStatics(gltf.scene);this.scene.add(gltf.scene);
 for(const t of [diff,norm,rough]){t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(80,80);t.anisotropy=this.renderer.capabilities.getMaxAnisotropy();}diff.colorSpace=T.SRGBColorSpace;
 const geo=createLunarTerrain();const regolith=new T.MeshStandardMaterial({color:0xc2c2c2,vertexColors:true,map:diff,normalMap:norm,roughnessMap:rough,roughness:1,normalScale:new T.Vector2(.8,.8)});
 // Keep scanned surface detail while removing the terrestrial brown cast.
 regolith.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\n diffuseColor.rgb = mix(vec3(dot(diffuseColor.rgb, vec3(0.2126, 0.7152, 0.0722))), diffuseColor.rgb, 0.08);');};regolith.customProgramCacheKey=()=> 'lunar-neutral-regolith-v2';
 const terrain=new T.Mesh(geo,regolith);terrain.receiveShadow=true;this.scene.add(terrain);
 let seed=732;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};rock.scene.updateMatrixWorld(true);const rockBounds=new T.Box3().setFromObject(rock.scene),size=rockBounds.getSize(new T.Vector3()).length();
 const placements:T.Matrix4[]=[];for(let i=0;i<650;i++){const x=(random()-.5)*680,z=(random()-.5)*680;if(x>-31&&x<34&&z>-35&&z<30||fieldSites.some(s=>Math.hypot(x-s.x,z-s.z)<18)||fieldRoutes.some(route=>route.slice(1).some((b,j)=>segmentDistance(x,z,route[j],b).distance<12)))continue;const scale=(.3+random()*2.5)/size;const placement=new T.Matrix4().compose(new T.Vector3(x,groundHeight(x,z)-.15,z),new T.Quaternion().setFromEuler(new T.Euler(0,random()*Math.PI*2,0)),new T.Vector3(scale,scale,scale));placements.push(placement);
 const bounds=rockBounds.clone().applyMatrix4(placement);if(bounds.max.y-groundHeight(x,z)>.22)this.obstacles.push({id:'moon-rock-'+i,x:(bounds.min.x+bounds.max.x)/2,z:(bounds.min.z+bounds.max.z)/2,hx:(bounds.max.x-bounds.min.x)/2,hz:(bounds.max.z-bounds.min.z)/2});}
 for(let i=0;i<6;i++){const x=-37+i*.9,z=8+Math.sin(i)*1.1,scale=(1.5+random()*1.5)/size;placements.push(new T.Matrix4().compose(new T.Vector3(x,groundHeight(x,z)-.2,z),new T.Quaternion().setFromEuler(new T.Euler(0,random()*6,0)),new T.Vector3(scale,scale*.8,scale)));}this.obstacles.push({id:'rock-outcrop',x:-34.7,z:8,hx:3.6,hz:2});
 rock.scene.traverse(o=>{if(o instanceof T.Mesh){
 const sourceMaterials=Array.isArray(o.material)?o.material:[o.material];
 for(const material of sourceMaterials){if(material instanceof T.MeshStandardMaterial){material.color.setHex(0xa8a8a8);material.roughness=1;material.onBeforeCompile=regolith.onBeforeCompile;material.customProgramCacheKey=()=> 'lunar-neutral-rock-v1';material.needsUpdate=true;}}
 const inst=new T.InstancedMesh(o.geometry,o.material,placements.length);placements.forEach((p,i)=>inst.setMatrixAt(i,p.clone().multiply(o.matrixWorld)));inst.castShadow=true;inst.receiveShadow=true;this.scene.add(inst);}});
 // Small embedded stones give the service yard a visible scale without blocking walking.
 const chips=new T.InstancedMesh(new T.IcosahedronGeometry(1,0),new T.MeshStandardMaterial({color:0x717274,roughness:1}),600);
 for(let i=0;i<600;i++){const x=(random()-.5)*85,z=(random()-.5)*85,scale=.025+random()*.075;chips.setMatrixAt(i,new T.Matrix4().compose(new T.Vector3(x,groundHeight(x,z)-.055,z),new T.Quaternion().setFromEuler(new T.Euler(random(),random()*6,random())),new T.Vector3(scale*1.4,scale*.55,scale)));}chips.receiveShadow=true;this.scene.add(chips);
 // A pair of shallow rover tread impressions lead toward the service apron.
 const treads=new T.InstancedMesh(new T.PlaneGeometry(.27,.065),new T.MeshStandardMaterial({color:0x343638,roughness:1,transparent:true,opacity:.24,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1}),180);
 for(let i=0;i<90;i++){const z=6+i*.22,x=-7+Math.sin(i*.022)*3;for(let side=0;side<2;side++){const xx=x+(side?1.38:-1.38);treads.setMatrixAt(i*2+side,new T.Matrix4().compose(new T.Vector3(xx,groundHeight(xx,z)-.043,z),new T.Quaternion().setFromEuler(new T.Euler(-Math.PI/2,0,-Math.cos(i*.022)*.22)),new T.Vector3(1,1,1)));}}this.scene.add(treads);
 earth.colorSpace=T.SRGBColorSpace;const globe=new T.Mesh(new T.SphereGeometry(175,64,48),new T.MeshStandardMaterial({map:earth,roughness:1,emissive:0x112d50,emissiveIntensity:.2}));globe.position.set(-1750,1950,-6000);globe.rotation.y=2.4;this.scene.add(globe);
 const field=buildFieldSites();batchMoonStatics(field.root);this.scene.add(field.root);this.obstacles.push(...field.colliders);
 try{const data=JSON.parse(localStorage.getItem('selene-field-v1')??'null');this.discoveries=validDiscoveries(data?.discoveries);if(data?.powerMode in powerProfiles)this.powerMode=data.powerMode;}catch{}
 this.loadingCleanups.clear();
 for(const task of missions){if(task.action==='open')continue;const [x,y,z]=task.point;if(this.taskLamps.some(l=>l.position.x===x&&l.position.z===z))continue;const lamp=new T.Mesh(new T.CylinderGeometry(.055,.055,.16,8),new T.MeshStandardMaterial({color:0x34434b,emissive:0x10212c,emissiveIntensity:.5}));lamp.position.set(x,Math.abs(x)<3.5&&z<-5.2?.8:groundHeight(x,z)+.6,z);lamp.userData.taskAction=task.action;const foot=lamp.position.y-.08,base=Math.abs(x)<3.5&&z<-5.2?.17:groundHeight(x,z)-.04;const post=new T.Mesh(new T.CylinderGeometry(.035,.05,foot-base,8),new T.MeshStandardMaterial({color:0x26313a,roughness:.8}));post.position.set(x,(foot+base)/2,z);this.scene.add(post,lamp);this.taskLamps.push(lamp);}
 this.greenhouseLight=new T.PointLight(0xb5e4da,0,10,2);this.greenhouseLight.position.set(-14,2.5,-6);this.scene.add(this.greenhouseLight);this.assetsReady=true;this.lastSessionSave=performance.now();this.notify();
 }
 private resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 setControlsPaused(paused:boolean){this.controlsPaused=paused;if(paused)this.driveSpeed=0;this.keys.clear();this.sprint.reset();this.drag=false;}
 lock(){if(this.dead||this.displayLost||this.controlsPaused)return;if(this.mode!=='walk')return;const c=this.renderer.domElement;c.focus({preventScroll:true});try{const p=c.requestPointerLock();if(p)void p.catch(()=>this.notify());}catch{this.notify();}}
 walk(){if(this.driving)return;this.targetFov=this.camera.fov=64;this.camera.updateProjectionMatrix();this.mode='walk';this.orbit.enabled=false;if(this.walkPose){this.camera.position.copy(this.walkPose.position);this.yaw=this.walkPose.yaw;this.pitch=this.walkPose.pitch;}else{this.camera.position.set(0,1.78,13);this.yaw=0;this.pitch=0;}this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');this.lock();this.notify();}
 overview(){if(this.driving&&!this.leaveRover())return;if(this.mode==='walk')this.walkPose={position:this.camera.position.clone(),yaw:this.yaw,pitch:this.pitch};this.targetFov=this.camera.fov=64;this.camera.updateProjectionMatrix();this.mode='overview';this.orbit.enabled=true;this.keys.clear();this.sprint.reset();if(document.pointerLockElement===this.renderer.domElement)document.exitPointerLock();this.camera.position.set(47,27,52);this.orbit.target.set(0,1,-3);this.orbit.update();this.notify();}
 private clearInteractionPath(target:T.Vector3,start=this.camera.position,allObstacles=false){
 // At walking eye height, opaque bulkheads block reach even when the target is nearby.
 return !this.obstacles.some(wall=>{
  if(!allObstacles&&!interactionWalls.has(wall.id))return false;
  let enter=0,exit=1;
  for(const [origin,delta,center,half] of [[start.x,target.x-start.x,wall.x,wall.hx],[start.z,target.z-start.z,wall.z,wall.hz]]){
   if(Math.abs(delta)<1e-8){if(origin<center-half||origin>center+half)return false;continue;}
   const a=(center-half-origin)/delta,b=(center+half-origin)/delta;
   enter=Math.max(enter,Math.min(a,b));exit=Math.min(exit,Math.max(a,b));if(enter>exit)return false;
  }
  return exit>1e-5&&enter<1-1e-5;
 });
 }
 private target(){if(this.state.complete)return undefined;const m=currentMission(this.state),p=interactionPoints[m.action],forward=new T.Vector3();this.camera.getWorldDirection(forward);return p.distanceTo(this.camera.position)<3.2&&p.clone().sub(this.camera.position).normalize().dot(forward)>.35&&this.clearInteractionPath(p)?[m.action,p,m.label] as [MoonAction,T.Vector3,string]:undefined;}
 interact(){if(this.mode==='flight')return;if(this.surveying){this.surveying=null;this.hooks.message('调查已取消。');return;}if(this.driving){this.leaveRover();return;}const target=this.target();if(!target){const site=this.fieldTarget();if(site){this.hooks.fieldChallenge?.(site.id);return;}if(this.canBoard()){this.boardRover();return;}this.hooks.message('靠近目标或月球车并面向它，再按 E 交互。');return;}this.action(target[0]);}
 action(action:MoonAction,calibration?:number){let message='';const navCommands:Record<string,NavTarget>={navigate_base:'base',navigate_station:'sample-station',navigate_lander:'lost-lander',navigate_crater:'crater-watch',navigate_mission:'mission'};if(navCommands[action]){this.setNavigation(navCommands[action]);return '已设置导航。';}if(action==='power_balanced'||action==='power_research'||action==='power_ecology'){this.setPowerMode(action.slice(6) as PowerMode);return this.state.solarRepaired?'已调整电力分配。':'需要先恢复主电源。';}if(action==='link'&&this.state.waterOnline&&powerProfiles[this.powerMode??'balanced'].comms<20)return '通信供电不足，请在基地系统中切换为均衡运行。';if(action==='overview'){this.overview();return '已切换基地全景。';}if(action==='walk'){this.walk();return '已进入月面探索。';}if(this.driving&&action!=='status')return '请先停车下车，再操作基地设备。';if(action==='recall'){this.roverGoal=new T.Vector3(0,0,6);message='月球车正在驶向气闸前的停泊点。';}else{const p=interactionPoints[action as keyof typeof interactionPoints];const distance=p?this.camera.position.distanceTo(p):0;if((action==='repair'||action==='link')&&currentMission(this.state).action===action&&!this.state.complete&&distance<=3.2&&this.clearInteractionPath(p)){const target=action==='repair'?48:132;if(!Number.isFinite(calibration)||Math.abs(calibration!-target)>(action==='repair'?.5:2)){this.hooks.challenge?.(action);return '请完成现场终端校准。';}}message=p&&distance<=3.2&&!this.clearInteractionPath(p)?'目标被舱壁挡住，请绕到目标正面。':missionAction(this.state,action,distance);}this.hooks.message(message);this.notify();return message;}
 private free(x:number,z:number){if(Math.abs(x)>EXPLORATION_LIMIT||Math.abs(z)>EXPLORATION_LIMIT)return false;if(Math.abs(x)<1.4&&Math.abs(z+5.2)<.5&&Math.abs(x)+.28>.005+this.door*1.15)return false;const rover=this.ids.get('rover');if(rover){const dx=x-rover.position.x,dz=z-rover.position.z,c=Math.cos(rover.rotation.y),s=Math.sin(rover.rotation.y);if(Math.abs(c*dx-s*dz)<1.9&&Math.abs(s*dx+c*dz)<2.2)return false;}return !this.obstacles.some(o=>Math.abs(x-o.x)<o.hx+.28&&Math.abs(z-o.z)<o.hz+.28);}
 private notify(){const player=this.mode==='overview'?this.walkPose?.position??new T.Vector3(0,1.78,13):this.driving?this.ids.get('rover')?.position??this.camera.position:this.camera.position,nav=this.navigation();const stage=currentMission(this.state);for(const lamp of this.taskLamps??[]){const index=missions.findIndex(m=>m.action===lamp.userData.taskAction),active=lamp.position.x===stage.point[0]&&lamp.position.z===stage.point[2],done=this.state.complete||index<missions.indexOf(stage);const material=lamp.material as T.MeshStandardMaterial;material.color.setHex(done?0x90c9ac:active?0x91dcff:0x34434b);material.emissive.copy(material.color);material.emissiveIntensity=done||active?1.5:.12;}if(this.greenhouseLight)this.greenhouseLight.intensity=this.state.waterOnline?12*powerProfiles[this.powerMode??'balanced'].ecology/33:0;const t=this.mode==='walk'?this.target():null;this.hooks.update({...this.state,objective:objective(this.state),hint:this.driving?'停车并下车':this.surveying?'取消调查':t?t[2]:this.fieldTarget()?.action??(this.canBoard()?'驾驶月球车':''),driving:this.driving??false,speed:Math.round(Math.abs(this.driveSpeed??0)*3.6),discoveries:this.discoveries??[],navTarget:this.navTarget??'mission',navLabel:nav.label,navDistance:Math.round(Math.hypot(nav.point[0]-player.x,nav.point[2]-player.z)),playerX:Math.round(player.x),playerZ:Math.round(player.z),bearing:Math.round((Math.atan2(nav.point[0]-player.x,player.z-nav.point[2])*180/Math.PI+360)%360),surveyProgress:this.surveying?Math.min(100,Math.round(this.surveyElapsed/surveyDuration(this.powerMode)*100)):-1,powerMode:this.powerMode??'balanced',flightSeconds:this.flightSeconds??0,distance:Math.round((this.driving?this.ids.get('rover')?.position??this.camera.position:this.camera.position).distanceTo(new T.Vector3(...missionTarget(this.state)))),mode:this.mode,locked:document.pointerLockElement===this.renderer.domElement});}
 private animate=(now:number)=>{this.frame=0;if(this.dead||this.displayLost||document.hidden)return;const before=this.camera.position.clone();const dt=Math.min(.04,(now-this.last)/1000);this.last=now;if(now-this.lastSessionSave>5000){this.lastSessionSave=now;this.persistSession();}
 this.holoDesk?.update(dt,this.state.powered);this.companion?.update(this.controlsPaused?0:dt,this.companionMood,this.camera.position,this.obstacles);if(this.mode==='flight'){this.updateFlight(dt);}this.updateSurvey(dt);
 if(this.mode==='walk'&&Math.abs(this.camera.fov-this.targetFov)>.01){this.camera.fov=T.MathUtils.damp(this.camera.fov,this.targetFov,12,dt);this.camera.updateProjectionMatrix();}
 if(this.mode==='walk'&&!this.driving){const wasLocked=this.sprint.locked;this.sprint.update(dt);if(!wasLocked&&this.sprint.locked)this.hooks.message('快跑已锁定，松开 Shift 可继续快跑；再按 Shift 取消。');const f=Number(this.keys.has('KeyW')||this.keys.has('ArrowUp'))-Number(this.keys.has('KeyS')||this.keys.has('ArrowDown')),r=Number(this.keys.has('KeyD')||this.keys.has('ArrowRight'))-Number(this.keys.has('KeyA')||this.keys.has('ArrowLeft')),v=dt*(this.sprint.active?5:2.8)/Math.max(1,Math.hypot(f,r));const p=this.camera.position,dx=(r*Math.cos(this.yaw)-f*Math.sin(this.yaw))*v,dz=(-f*Math.cos(this.yaw)-r*Math.sin(this.yaw))*v;if(this.free(p.x+dx,p.z))p.x+=dx;if(this.free(p.x,p.z+dz))p.z+=dz;this.updateElevation(dt);}else if(this.mode==='overview')this.orbit.update();
 this.door=T.MathUtils.damp(this.door,this.state.doorOpen?1:0,2,dt);const left=this.ids.get('door-left'),right=this.ids.get('door-right');if(left)left.position.x=-.58-this.door*1.15;if(right)right.position.x=.58+this.door*1.15;
 const battery=this.ids.get('battery');if(battery)battery.visible=!this.state.carrying&&!this.state.powered;this.updateLighting(dt);
 const light=this.ids.get('power-light') as T.Mesh|undefined;if(light){const m=light.material as T.MeshStandardMaterial;m.emissive.setHex(this.state.powered?0x66d9b0:0x221100);m.emissiveIntensity=this.state.powered?2:.4;}
 if(this.mode!=='flight')this.updateRover(dt);
 if(this.sunlight){const follow=this.mode==='walk'?(this.driving?this.ids.get('rover')?.position??this.camera.position:this.camera.position):new T.Vector3();this.sunlight.target.position.copy(follow);this.sunlight.position.copy(follow).add(new T.Vector3(-45,28,35));}
 const target=this.navigation().point;this.ring.position.set(target[0],(Math.abs(target[0])<3.5&&target[2]<-5.2&&target[2]>-19?.17:groundHeight(target[0],target[2])-.05)+.012,target[2]);this.ring.visible=this.mode!=='flight'&&(!this.state.complete||this.navTarget!=='mission');this.ring.scale.setScalar(1+Math.sin(now*.003)*.06);
 if(now-this.updateAt>120){this.updateAt=now;this.notify();}this.hooks.audio?.({dt,distance:Math.hypot(this.camera.position.x-before.x,this.camera.position.z-before.z),indoor:Math.abs(this.camera.position.x)<4&&this.camera.position.z<-5.2&&this.camera.position.z>-32,powered:this.state.powered,driving:this.driving,speed:this.driveSpeed,active:this.mode==='walk'&&!this.controlsPaused&&!document.hidden&&(document.hasFocus()||document.pointerLockElement===this.renderer.domElement)});this.renderer.render(this.scene,this.camera);this.frame=requestAnimationFrame(this.animate);};
 private updateElevation(dt:number){const p=this.camera.position;const interior=(Math.abs(p.x)<3.4&&p.z<-5.2&&p.z>-18.7)||(Math.abs(p.x)<1.35&&p.z<=-18.7&&p.z>-22)||(Math.abs(p.x)<3.85&&p.z<=-22&&p.z>-32);p.y=T.MathUtils.damp(p.y,(interior?.17:groundHeight(p.x,p.z))+1.78,9.75,dt);return interior;}
 private updateRover(dt:number){
 if(this.driving){this.updateDriving(dt);return;}const rover=this.ids.get('rover');if(!rover||!this.roverGoal)return;
 const delta=this.roverGoal.clone().sub(rover.position);delta.y=0;const distance=delta.length();
 if(distance<.025){this.roverGoal=null;return;}
 if(this.mode==='walk'&&Math.hypot(this.camera.position.x-rover.position.x,this.camera.position.z-rover.position.z)<3.4)return;
 // The authored headlights face local +Z. Turn before advancing along the route.
 const heading=Math.atan2(delta.x,delta.z),error=Math.atan2(Math.sin(heading-rover.rotation.y),Math.cos(heading-rover.rotation.y));
 const turn=T.MathUtils.clamp(error,-dt*1.3,dt*1.3);const nextYaw=rover.rotation.y+turn;
 const travel=Math.abs(error-turn)<.08?Math.min(distance,dt*1.2):0;
 const next=rover.position.clone().add(delta.clone().normalize().multiplyScalar(travel));if(!roverFits(next.x,next.z,nextYaw,this.obstacles??[],groundHeight)){this.roverGoal=null;this.hooks.message('月球车前方受阻，请到车辆旁手动驾驶。');return;}rover.rotation.y=nextYaw;rover.position.copy(next);this.seatRoverOnGround(rover);
 for(const [id,wheel] of this.ids)if(id.startsWith('wheel-'))wheel.rotateX((travel-wheel.position.x*turn)/.59);
 }

 restart(){this.finishLaunch(false);this.discoveries=[];this.powerMode='balanced';this.navTarget='mission';this.surveying=null;this.saveField();this.state=initialState();this.driving=false;this.driveSpeed=0;this.roverGoal=null;this.walkPose=null;this.mode='overview';const rover=this.ids.get('rover');if(rover){rover.position.set(-7,-.06,5);rover.rotation.set(0,0,0,'YXZ');}this.setControlsPaused(false);this.overview();this.persistSession();}
 private canBoard(){const rover=this.ids.get('rover');if(!rover||this.mode!=='walk'||this.driving)return false;const delta=rover.position.clone().add(new T.Vector3(0,1.2,0)).sub(this.camera.position),forward=new T.Vector3();this.camera.getWorldDirection(forward);return delta.length()<4.2&&delta.normalize().dot(forward)>.25&&this.clearInteractionPath(rover.position);}
 private boardRover(){if(!this.canBoard())return;this.roverGoal=null;this.driveSpeed=0;this.driving=true;this.keys.clear();this.sprint.reset();this.targetFov=this.camera.fov=64;this.camera.updateProjectionMatrix();this.updateDriving(0);this.hooks.message('已登上月球车。W/S 前进倒车，A/D 转向，空格刹车，E 下车。');this.lock();this.notify();}
 private leaveRover(){const rover=this.ids.get('rover');if(!rover||!this.driving)return true;if(Math.abs(this.driveSpeed)>.3){this.hooks.message('请先松开油门或按空格刹停，再下车。');return false;}const c=Math.cos(rover.rotation.y),s=Math.sin(rover.rotation.y);for(const [a,b] of [[3,0],[-3,0],[0,-3.4],[0,3.4],[3,-3],[-3,-3]]){const x=rover.position.x+c*a+s*b,z=rover.position.z-s*a+c*b;if(!this.free(x,z)||!this.clearInteractionPath(new T.Vector3(x,1.78,z),rover.position,true))continue;this.driving=false;this.driveSpeed=0;this.camera.position.set(x,groundHeight(x,z)+1.78,z);this.yaw=rover.rotation.y+Math.PI;this.pitch=0;this.camera.rotation.set(0,this.yaw,0,'YXZ');this.walkPose={position:this.camera.position.clone(),yaw:this.yaw,pitch:0};this.keys.clear();this.sprint.reset();this.hooks.message('已停稳下车，携带物品仍在背包中。');this.notify();return true;}this.hooks.message('车旁没有安全落脚点，请移到开阔位置再下车。');return false;}
 private seatRoverOnGround(rover:T.Object3D){const c=Math.cos(rover.rotation.y),s=Math.sin(rover.rotation.y),x=rover.position.x,z=rover.position.z;const front=groundHeight(x+s*1.5,z+c*1.5),back=groundHeight(x-s*1.5,z-c*1.5),right=groundHeight(x+c*1.38,z-s*1.38),left=groundHeight(x-c*1.38,z+s*1.38);rover.position.y=(front+back+right+left)/4-.06;rover.rotation.order='YXZ';rover.rotation.x=-Math.atan2(front-back,3);rover.rotation.z=Math.atan2(right-left,2.76);}
 private updateDriving(dt:number){const rover=this.ids.get('rover');if(!rover)return;const held=(...codes:string[])=>codes.some(k=>this.keys.has(k));const result=advanceRover({x:rover.position.x,z:rover.position.z,yaw:rover.rotation.y,speed:this.driveSpeed},{throttle:this.controlsPaused?0:Number(held('KeyW','ArrowUp'))-Number(held('KeyS','ArrowDown')),steer:this.controlsPaused?0:Number(held('KeyA','ArrowLeft'))-Number(held('KeyD','ArrowRight')),brake:this.controlsPaused||held('Space')},dt,this.obstacles,groundHeight);this.driveSpeed=result.pose.speed;rover.position.x=result.pose.x;rover.position.z=result.pose.z;rover.rotation.y=result.pose.yaw;this.seatRoverOnGround(rover);for(const [id,wheel] of this.ids)if(id.startsWith('wheel-'))wheel.rotateX((result.travel-wheel.position.x*result.turn)/.59);if(result.blocked&&!this.driveBlocked)this.hooks.message('前方有障碍或坡度过大，请倒车绕行。');this.driveBlocked=result.blocked;const front=new T.Vector3(Math.sin(rover.rotation.y),0,Math.cos(rover.rotation.y)),look=rover.position.clone().addScaledVector(front,2).add(new T.Vector3(0,1.5,0)),eye=rover.position.clone().addScaledVector(front,-this.chaseDistance).add(new T.Vector3(0,4,0));eye.y=Math.max(eye.y,groundHeight(eye.x,eye.z)+1.2);const ray=new T.Raycaster(look,eye.clone().sub(look).normalize(),0,look.distanceTo(eye));const hit=this.model?ray.intersectObject(this.model,true).find(h=>{let o:T.Object3D|null=h.object;while(o){if(o===rover||o.userData.glazing)return false;o=o.parent;}return true;}):undefined;if(hit)eye.copy(ray.ray.at(Math.max(.6,hit.distance-.3),new T.Vector3()));this.camera.position.copy(eye);this.camera.lookAt(look);}
 private updateLighting(dt:number){
 const doorMoving=Math.abs(this.door-(this.state.doorOpen?1:0))>.001;
 const switched=this.lightingPowered!==this.state.powered;
 for(const light of this.roofLights){light.intensity=T.MathUtils.damp(light.intensity,this.state.powered?(light.userData.nominalIntensity??26)*powerProfiles[this.powerMode??'balanced'].research/34:0,2,dt);if(switched||doorMoving)light.shadow.needsUpdate=true;}
 this.lightingPowered=this.state.powered;
 }


 private exitPoint(){const rover=this.ids.get('rover');if(!rover)return null;const c=Math.cos(rover.rotation.y),s=Math.sin(rover.rotation.y);for(const [a,b] of [[3,0],[-3,0],[0,-3.4],[0,3.4],[3,-3],[-3,-3]]){const x=rover.position.x+c*a+s*b,z=rover.position.z-s*a+c*b;if(this.free(x,z)&&this.clearInteractionPath(new T.Vector3(x,1.78,z),rover.position,true))return new T.Vector3(x,groundHeight(x,z)+1.78,z);}return null;}
 private persistSession(){if(!this.assetsReady||this.dead)return;const rover=this.ids.get('rover'),fallback=this.walkPose??{position:new T.Vector3(0,1.78,13),yaw:0,pitch:0};const position=this.driving?this.exitPoint()??fallback.position:this.mode==='walk'?this.camera.position:fallback.position;const save:MoonSession={version:1,player:{x:position.x,z:position.z,yaw:this.driving?(rover?.rotation.y??0)+Math.PI:this.mode==='walk'?this.yaw:fallback.yaw,pitch:this.driving?0:this.mode==='walk'?this.pitch:fallback.pitch},rover:rover?{x:rover.position.x,z:rover.position.z,yaw:rover.rotation.y}:null,nav:this.navTarget};try{localStorage.setItem('selene-session-v1',JSON.stringify(save));}catch{}}
 restoreSession(){if(!this.assetsReady)return;let saved:MoonSession|null=null;try{saved=readSession(JSON.parse(localStorage.getItem('selene-session-v1')??'null'));}catch{}if(!saved)return;const rover=this.ids.get('rover');if(rover&&saved.rover&&roverFits(saved.rover.x,saved.rover.z,saved.rover.yaw,this.obstacles,groundHeight)){rover.position.set(saved.rover.x,0,saved.rover.z);rover.rotation.y=saved.rover.yaw;this.seatRoverOnGround(rover);}const p=saved.player,inside=Math.abs(p.x)<4&&p.z<-5.2&&p.z>-32;if(this.free(p.x,p.z)&&(!inside||this.state.doorOpen))this.walkPose={position:new T.Vector3(p.x,(inside?.17:groundHeight(p.x,p.z))+1.78,p.z),yaw:p.yaw,pitch:p.pitch};this.navTarget=saved.nav;this.driveSpeed=0;this.roverGoal=null;this.lastSessionSave=performance.now();this.notify();}

 setAssistantActivity(open:boolean,busy:boolean){this.companionMood=open?(busy?'thinking':'listening'):'idle';}
 applySettings(settings:MoonSettings){this.sensitivity=settings.sensitivity;this.renderer.setPixelRatio(Math.min(devicePixelRatio,settings.quality==='balanced'?1:2));this.resize();}
 prepareArrival(){let saved=null;try{saved=readSession(JSON.parse(localStorage.getItem('selene-session-v1')??'null'));}catch{}if(!saved&&!this.state.powered&&!this.state.carrying)this.walkPose={position:new T.Vector3(22,groundHeight(22,24)+1.78,24),yaw:1.1,pitch:0};}
 recover(){if(this.mode==='flight')return;const spots=[[0,6],[0,13],[6,10],[-6,10]];const spot=spots.find(([x,z])=>this.free(x,z));if(!spot){this.hooks.message('气闸附近暂时没有安全位置，请稍后重试。');return;}this.driving=false;this.driveSpeed=0;this.roverGoal=null;this.surveying=null;this.keys.clear();this.sprint.reset();const [x,z]=spot;this.camera.position.set(x,groundHeight(x,z)+1.78,z);this.yaw=0;this.pitch=0;this.camera.rotation.set(0,0,0);this.walkPose={position:this.camera.position.clone(),yaw:0,pitch:0};this.mode='walk';this.orbit.enabled=false;this.persistSession();this.notify();this.hooks.message('已返回气闸附近。任务、携带物品和车辆位置均已保留。');}
 completeFieldChallenge(id:FieldSiteId,answer:unknown){if(this.surveying||this.mode!=='walk'||this.driving||this.fieldTarget()?.id!==id||!solveField(id,answer))return false;this.surveying=id;this.surveyElapsed=0;this.hooks.message('现场操作完成，正在采集调查记录。');return true;}
 private saveField(){try{localStorage.setItem('selene-field-v1',JSON.stringify({discoveries:this.discoveries,powerMode:this.powerMode}));}catch{this.hooks.message('本次调查记录无法写入浏览器存档。');}}
 setNavigation(target:NavTarget){if(target!=='mission'&&target!=='base'&&!fieldSites.some(s=>s.id===target))return;this.navTarget=target;this.hooks.message('导航目标：'+this.navigation().label);this.notify();}
 private navigation(){if(this.navTarget==='base')return {label:'返回基地气闸',point:[0,1,3] as [number,number,number]};const site=fieldSites.find(s=>s.id===this.navTarget);return site?{label:site.name,point:[site.x,groundHeight(site.x,site.z)+1.3,site.z+4.5] as [number,number,number]}:{label:'当前主线目标',point:missionTarget(this.state)};}
 private fieldTarget(){if(this.mode!=='walk'||this.driving)return undefined;const forward=new T.Vector3();this.camera.getWorldDirection(forward);return fieldSites.find(s=>!(this.discoveries??[]).includes(s.id)&&(()=>{const p=new T.Vector3(s.x,groundHeight(s.x,s.z)+1.3,s.z+3.7),d=p.clone().sub(this.camera.position);return d.length()<4&&d.normalize().dot(forward)>.25&&this.clearInteractionPath(p);})());}
 private updateSurvey(dt:number){if(!this.surveying||this.controlsPaused)return;const site=fieldSites.find(s=>s.id===this.surveying);if(!site||this.driving||this.mode!=='walk'||Math.hypot(this.camera.position.x-site.x,this.camera.position.z-site.z-3.7)>5){this.surveying=null;this.hooks.message('已离开终端，调查中断。');return;}this.surveyElapsed+=dt;if(this.surveyElapsed>=surveyDuration(this.powerMode)){this.discoveries=validDiscoveries([...this.discoveries,site.id]);this.surveying=null;this.saveField();this.hooks.message(this.discoveries.length===fieldSites.length?'三处调查完成，已获得「月面勘探员」记录。':site.report);this.notify();}}
 setPowerMode(mode:PowerMode){if(!(mode in powerProfiles))return;if(!this.state.solarRepaired){this.hooks.message('请先修复太阳能主回路，再分配基地电力。');return;}this.powerMode=mode;this.saveField();this.hooks.message('已切换为'+powerProfiles[mode].name+'。');this.notify();}
 startLaunch(){if(!this.state.complete){this.hooks.message('请先完成基地复苏任务。');return;}if(this.driving||this.mode==='flight'||!this.flightShip)return;if(this.mode!=='walk'||Math.hypot(this.camera.position.x-22,this.camera.position.z-18)>10){this.hooks.message('请步行返回飞船旁，再启动起飞演出。');return;}this.walkPose={position:this.camera.position.clone(),yaw:this.yaw,pitch:this.pitch};this.surveying=null;this.roverGoal=null;this.flightSeconds=0;this.mode='flight';this.setControlsPaused(true);if(document.pointerLockElement)document.exitPointerLock();this.orbit.enabled=false;const plume=new T.Mesh(new T.ConeGeometry(.85,3,24),new T.MeshBasicMaterial({color:0x9bd8ff,transparent:true,opacity:.7,depthWrite:false,blending:T.AdditiveBlending}));plume.position.set(0,-.6,0);this.flightShip.add(plume);this.plume=plume;this.hooks.message('起飞检查完成，准备点火。');this.notify();}
 finishLaunch(showMessage=true){if(this.plume){this.plume.removeFromParent();this.plume.geometry.dispose();(this.plume.material as T.Material).dispose();this.plume=null;}if(this.flightShip)this.flightShip.position.y=0;if(this.mode==='flight'){this.mode='overview';this.setControlsPaused(false);this.overview();if(showMessage)this.hooks.message('起飞演出结束，已返回基地自由探索。');}}
 private updateFlight(dt:number){if(!this.flightShip)return;this.flightSeconds+=dt;const t=this.flightSeconds,h=launchAltitude(t);this.flightShip.position.y=h;if(this.plume){this.plume.visible=t>=2;this.plume.scale.y=1+Math.sin(t*35)*.08;}const angle=t*.055;this.camera.position.set(22+Math.cos(angle)*22,h+10,18+Math.sin(angle)*22);this.camera.lookAt(22,h+4,18);if(t>=20)this.finishLaunch();}
 private release(root:T.Object3D){const gs=new Set<T.BufferGeometry>(),ms=new Set<T.Material>(),ts=new Set<T.Texture>();root.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line){gs.add(o.geometry);for(const m of Array.isArray(o.material)?o.material:[o.material]){ms.add(m);for(const v of Object.values(m))if(v instanceof T.Texture)ts.add(v);}}});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());}
 dispose(){if(this.dead)return;this.persistSession();this.dead=true;for(const cleanup of this.loadingCleanups)cleanup();this.loadingCleanups.clear();cancelAnimationFrame(this.frame);this.signal.abort();this.resizeObserver.disconnect();if(document.pointerLockElement===this.renderer.domElement)document.exitPointerLock();this.orbit.dispose();this.scene.traverse(o=>{if(o instanceof T.Light&&'shadow' in o)(o as T.PointLight).shadow.dispose();});this.release(this.scene);this.env?.dispose();this.pmrem?.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}





