import React,{useState} from 'react';
import {Archive,FileText,Check} from 'lucide-react';
import {fieldArchives} from './moon-field-archives';
import {lunarUiAsset,SignalWave} from './moon-interface';
import type {AdventureState} from './moon-adventure';
export function FieldArchives({state,initialId}:{state:AdventureState;initialId?:string}){
 const records=fieldArchives(state),[selected,setSelected]=useState(initialId??'');
 const record=records.find(r=>r.id===selected)??records[0];
 if(!record)return <div className="moon-empty-archive"><Archive size={46}/><small>SELENE / ARCHIVE</small><h3>等待第一份发现</h3><p>回收未知信号中的存储芯片，在工作室解码。<br/>你的发现会成为可以反复阅读的基地档案。</p><span>尚无已解锁档案</span></div>;
 return <div className="moon-archive-workspace"><nav className="moon-file-index" aria-label="已解锁档案"><small>回收档案 / {String(records.length).padStart(2,'0')}</small>{records.map(r=><button key={r.id} aria-pressed={record.id===r.id} onClick={()=>setSelected(r.id)}><small>{r.id==='distant-echo'?'SIG—001':r.id==='lunar-geologist'?'COL—001':`GEO—${String(['basalt','breccia','anorthosite'].indexOf(r.id)+1).padStart(3,'0')}`}</small><strong>{r.title}</strong><span>{r.category}</span></button>)}<div className="moon-file-index-foot"><FileText size={16}/> 发现与记录，保存在这里。</div></nav><article key={record.id} className="moon-archive-reader"><div className={'moon-archive-cover'+(record.id==='distant-echo'?'':' is-report')}>{record.id==='distant-echo'?<img src={lunarUiAsset('archive-distant-echo-v1.png')} alt="月面上遗留的受损探测器，档案主题插画"/>:<div className="moon-report-cover"><FileText size={44}/><span>SELENE / FIELD SCIENCE</span><strong>{record.title}</strong><small>已完成的月面研究记录</small></div>}<span className="moon-photo-label">SELENE ARCHIVE / {record.id==='distant-echo'?'SIG—001':'GEOLOGICAL RECORD'}</span></div>{record.id==='distant-echo'&&<div className="moon-archive-wave"><SignalWave/><span>142.4 MHz</span></div>}<small className="moon-record-category">{record.category}</small><h3>{record.title}</h3><p className="moon-record-summary">{record.summary}</p><p className="moon-archive-source">{record.source}</p>{record.sections.map(section=><section key={section.heading}><h4>{section.heading}</h4><p>{section.text}</p></section>)}<footer className="moon-record-footer"><span className="moon-record-check"><Check size={19}/></span><div>档案已解锁<small>已归档 · 随探索存档保留</small></div></footer></article></div>;
}
