import {describe,it,expect} from 'vitest';
import {freshAdventure,restoreAdventure,applyAdventure,signalReading,signalPoint,researchPoint,rockSamples} from '../app/moon-adventure';
import {advanceRover} from '../app/moon-driving';
const context=(p={x:0,z:0},powered=true)=>({...p,powered,onFoot:true});
describe('adventure complete loops',()=>{
 it('detects once, requires the source and correct tuning, then requires powered lab to decode',()=>{const s=freshAdventure();expect(applyAdventure(s,{kind:'detect'},context())).toBe(true);expect(applyAdventure(s,{kind:'detect'},context())).toBe(false);expect(applyAdventure(s,{kind:'recover',frequency:142.4},context())).toBe(false);expect(applyAdventure(s,{kind:'recover',frequency:141},context(signalPoint))).toBe(false);expect(applyAdventure(s,{kind:'recover',frequency:142.4},context(signalPoint))).toBe(true);expect(applyAdventure(s,{kind:'decode'},context(signalPoint))).toBe(false);expect(applyAdventure(s,{kind:'decode'},context(researchPoint,false))).toBe(false);expect(applyAdventure(s,{kind:'decode'},context(researchPoint))).toBe(true);expect(applyAdventure(s,{kind:'decode'},context(researchPoint))).toBe(false);expect(restoreAdventure(JSON.parse(JSON.stringify(s)))).toEqual(s);});
 it('collects three unique rocks, rejects wrong classification, and restores completed research',()=>{const s=freshAdventure();for(const r of rockSamples){expect(applyAdventure(s,{kind:'collect',id:r.id},context(r))).toBe(true);expect(applyAdventure(s,{kind:'collect',id:r.id},context(r))).toBe(false);expect(applyAdventure(s,{kind:'study',id:r.id,answer:r.answer},context(r))).toBe(false);expect(applyAdventure(s,{kind:'study',id:r.id,answer:'wrong'},context(researchPoint))).toBe(false);expect(applyAdventure(s,{kind:'study',id:r.id,answer:r.answer},context(researchPoint))).toBe(true);expect(applyAdventure(s,{kind:'study',id:r.id,answer:r.answer},context(researchPoint))).toBe(false);}expect(s.studied.length).toBe(3);expect(restoreAdventure(JSON.parse(JSON.stringify(s)))).toEqual(s);});
 it('does not allow collection from a vehicle or fabricated save rewards',()=>{const s=freshAdventure();expect(applyAdventure(s,{kind:'collect',id:'basalt'},{...context(rockSamples[0]),onFoot:false})).toBe(false);expect(restoreAdventure({version:1,signal:'broken',samples:['basalt','basalt','x'],studied:['breccia','basalt']})).toEqual({version:1,signal:'idle',samples:['basalt'],studied:['basalt']});});
 it('signal gets stronger on approach and research extends receiver range',()=>{const s=freshAdventure();s.signal='active';expect(signalReading(s,-95,-65)).toBe(100);expect(signalReading(s,80,-65)).toBe(0);s.studied=['basalt'];expect(signalReading(s,80,-65)).toBeGreaterThan(0);});
});
describe('faster rover safety',()=>{
 it('reaches 36 km/h and brakes within four metres',()=>{let p={x:0,z:0,yaw:0,speed:0};for(let i=0;i<150;i++)p=advanceRover(p,{throttle:1,steer:0,brake:false},.04,[],()=>0).pose;expect(p.speed).toBe(10);const z=p.z;for(let i=0;i<20;i++)p=advanceRover(p,{throttle:0,steer:0,brake:true},.04,[],()=>0).pose;expect(p.speed).toBe(0);expect(p.z-z).toBeLessThan(4);});
 it('stops at collision at top speed and reduces high-speed steering',()=>{const p={x:0,z:0,yaw:0,speed:10};const result=advanceRover(p,{throttle:1,steer:0,brake:false},.04,[{x:0,z:2.7,hx:3,hz:.3}],()=>0);expect(result.blocked).toBe(true);expect(result.pose.speed).toBe(0);const slow=advanceRover({...p,speed:3},{throttle:0,steer:1,brake:false},.04,[],()=>0);const fast=advanceRover(p,{throttle:1,steer:1,brake:false},.04,[],()=>0);expect(fast.turn).toBeLessThan(slow.turn);});
});
