import * as E from './editing.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const label=(ref,index=0)=>({wall:`墙体 ${index+1}`,opening:ref.o.type==='door'?'门':'窗',room:ref.o.name||'分区',furniture:ref.o.name||'家具',stair:'楼梯',solid:ref.o.name||'自建构件'}[ref.kind]);
const input=(name,id,value,extra='')=>`<label class="field"><span>${name}</span><input id="${id}" aria-label="${name}" type="number" value="${value}" ${extra}></label>`;
export function selectionTools(f,refs){
 if(!refs.length)return '';
 const locked=refs.some(r=>E.locked(f,r)),groups=new Set(refs.map(r=>E.entity(f,r)?.groupId).filter(Boolean)),group=groups.size===1&&refs.every(r=>E.entity(f,r)?.groupId),name=group?E.entity(f,refs[0]).groupName:`选中 ${refs.length} 个构件`;
 return `<section class="section selection-tools"><h2 class="section-title">${esc(name)} <span class="selection-tag">${locked?'已锁定':refs.length+' 项'}</span></h2><div class="edit-button-grid"><button class="btn small" data-edit="group" ${locked||refs.length<2?'disabled':''}>成组</button><button class="btn small" data-edit="ungroup" ${locked||!groups.size?'disabled':''}>解组</button><button class="btn small" data-edit="hide">隐藏</button><button class="btn small" data-edit="lock">${locked?'解锁':'锁定'}</button></div>${locked?'<p class="muted">解锁后可移动或修改。隐藏、锁定状态会随项目保存。</p>':`<details class="edit-details" ${refs.length>1?'open':''}><summary>精确移动、旋转与复制</summary><div class="field-row">${input('左右移动 / mm','moveX',0,'step="100" min="-500000" max="500000"')}${input('上下移动 / mm','moveY',0,'step="100" min="-500000" max="500000"')}</div><p class="muted tight">正数向右 / 向下，负数向左 / 向上。</p><button class="btn full" data-edit="move">移动选中</button><div class="field-row">${input('旋转角度 / °','rotateBy',90,'step="15" min="-360" max="360"')}<button class="btn small field-button" data-edit="rotate">绕中心旋转</button></div><div class="edit-button-grid"><button class="btn small" data-edit="mirrorX">左右镜像</button><button class="btn small" data-edit="mirrorY">上下镜像</button></div><label class="toggle-row">保留原件，生成镜像副本<input type="checkbox" id="mirrorCopy"></label><div class="edit-subtitle">等距复制</div><div class="field-row">${input('横向间距 / mm','copyX',1000,'step="100" min="-500000" max="500000"')}${input('纵向间距 / mm','copyY',0,'step="100" min="-500000" max="500000"')}</div><div class="field-row">${input('新增份数','copyCount',1,'min="1" max="50" step="1"')}<button class="btn small field-button" data-edit="array">等距复制</button></div><p class="muted tight">间距按相同位置之间的距离计算；门窗沿所属墙复制。</p><div class="edit-subtitle">离墙距离</div><div class="field-row"><label class="field"><span>墙的方向</span><select id="wallSide" aria-label="墙的方向"><option value="left">左侧墙</option><option value="right">右侧墙</option><option value="top">上侧墙</option><option value="bottom">下侧墙</option></select></label>${input('离墙净距 / mm','wallGap',600,'min="0" max="100000" step="100"')}</div><button class="btn full" data-edit="clearance">按净距移动</button></details><div class="action-row"><button class="btn small" data-edit="copy">复制一份</button><button class="btn small danger" data-edit="delete">删除选中</button><button class="btn small" data-edit="clear">取消</button></div>`}</section>`;
}
export function objectList(f,refs,filter='all'){
 const chosen=new Set(refs.map(r=>r.id)),all=E.entities(f),rows=all.filter(r=>filter==='all'||r.kind===filter);
 return `<section class="section object-panel"><h2 class="section-title">构件列表 <small>当前楼层 · ${all.length} 项</small></h2><p class="muted">Shift 点选可多选；点击组合里的任一构件会选中整组。锁定后仍可在列表中选择、解锁。</p><label class="field"><select id="objectFilter" aria-label="构件筛选">${[['all','全部构件'],['furniture','家具'],['wall','墙体'],['opening','门窗'],['room','房间地面'],['stair','楼梯'],['solid','自建构件']].map(([v,n])=>`<option value="${v}" ${v===filter?'selected':''}>${n}</option>`).join('')}</select></label><div class="edit-button-grid"><button class="btn small" data-edit="selectFiltered">选中当前分类</button><button class="btn small" data-edit="editSelected" ${!refs.length?'disabled':''}>编辑选中 ${refs.length||''}</button></div><div class="object-rows">${f.image?`<div class="object-row"><span class="object-label">图纸底图</span><button class="object-state" data-image-state="hidden" aria-label="${f.image.hidden?'显示':'隐藏'}底图">${f.image.hidden?'显示':'隐藏'}</button><button class="object-state" data-image-state="locked" aria-label="${f.image.locked?'解锁':'锁定'}底图">${f.image.locked?'解锁':'锁定'}</button></div>`:''}${rows.map((r,i)=>`<div class="object-row ${chosen.has(r.id)?'chosen':''} ${E.hidden(f,r)?'is-hidden':''}" data-object="${r.id}"><button class="object-label" data-select-id="${r.id}" data-select-kind="${r.kind}" aria-pressed="${chosen.has(r.id)}" title="${esc(label(r,i))}">${esc(label(r,i))}${r.o.groupId?`<small>${esc(r.o.groupName||'组合')}</small>`:''}</button><button class="object-state ${E.hidden(f,r)?'on':''}" data-flag="hidden" data-ref-id="${r.id}" data-ref-kind="${r.kind}" aria-label="${E.hidden(f,r)?'显示':'隐藏'}${esc(label(r,i))}">${E.hidden(f,r)?'显示':'隐藏'}</button><button class="object-state ${E.locked(f,r)?'on':''}" data-flag="locked" data-ref-id="${r.id}" data-ref-kind="${r.kind}" aria-label="${E.locked(f,r)?'解锁':'锁定'}${esc(label(r,i))}">${E.locked(f,r)?'解锁':'锁定'}</button></div>`).join('')||'<p class="muted">此分类暂无构件</p>'}</div><div class="edit-button-grid"><button class="btn small" data-edit="showAllObjects">全部显示</button><button class="btn small" data-edit="unlockAll">全部解锁</button></div></section>`;
}
export function guidePanel(f,axis='x'){
 return `<section class="section guide-panel"><h2 class="section-title">参考线 <small>随项目保存</small></h2><p class="muted">选择方向后点击画布放置，或输入精确位置。拖动虚线可以调整；开启吸附后，墙端和家具可对齐参考线。</p><label class="field"><span>参考线方向</span><select id="guideAxis" aria-label="参考线方向"><option value="x" ${axis==='x'?'selected':''}>竖向 · X 坐标</option><option value="y" ${axis==='y'?'selected':''}>横向 · Y 坐标</option></select></label>${input('参考线位置 / mm','guidePosition',0,'step="100" min="-500000" max="500000"')}<button class="btn full" data-edit="addGuide">按位置添加参考线</button><button class="btn small full" data-edit="exitGuide">完成放置</button><div class="guide-rows">${(f.guides||[]).map(g=>`<div class="guide-row" data-guide-row="${g.id}"><span>${g.axis.toUpperCase()}</span><input type="number" aria-label="参考线 ${g.axis.toUpperCase()} 位置 / mm" data-guide-value="${g.id}" value="${Math.round(g.value*1000)}" ${g.locked?'disabled':''} min="-500000" max="500000" step="100"><button class="object-state" data-guide-lock="${g.id}">${g.locked?'解锁':'锁定'}</button><button class="object-state danger" data-guide-delete="${g.id}" ${g.locked?'disabled':''}>删除</button></div>`).join('')}</div></section>`;
}
