import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {STLExporter} from 'three/addons/exporters/STLExporter.js';
import {configureAssets,buildFurniture,floorMat,mat,box} from './assets.js';
import {bounds,length,onWall,projection,pointIn,centroid,area,wallCells,floorElevation,clamp} from './model.js';
import {download} from './download.js';
import {locked} from './editing.js';
import {doorPose} from './openings.js';
import {solidGeometry} from './modeling-mesh.js';
import {installModelingViewer} from './modeling-viewer.js';
import {findWalkStart,walkBlocked} from './walk-navigation.js';

export class Viewer {
 constructor(host,onSelect,onStatus){
  this.host=host;this.onSelect=onSelect;this.onStatus=onStatus;this.keys=new Set();this.options={floor:'all',exploded:false,cut:false,furniture:true,blueprint:true,night:false,includeHidden:false};this.doorStates=new Map();this.walk=false;this.yaw=0;this.pitch=0;this.selected=null;this.last=performance.now();
  this.renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.9;host.append(this.renderer.domElement);configureAssets(this.renderer);
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#f1efeb');this.camera=new THREE.PerspectiveCamera(43,1,.05,1500);this.orbit=new OrbitControls(this.camera,this.renderer.domElement);this.orbit.enableDamping=true;this.orbit.minDistance=1;this.orbit.maxDistance=180;this.orbit.maxPolarAngle=Math.PI*.49;
  const env=new THREE.PMREMGenerator(this.renderer);this.environment=env.fromScene(new RoomEnvironment(),.04);this.scene.environment=this.environment.texture;this.scene.environmentIntensity=.4;env.dispose();
  this.hemi=new THREE.HemisphereLight(0xffffff,0xc3c7b8,2);this.scene.add(this.hemi);this.sun=new THREE.DirectionalLight(0xfff7e9,3.2);this.sun.position.set(-8,18,10);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:.5,far:120});this.sun.shadow.normalBias=.035;this.scene.add(this.sun,this.sun.target);
  this.model=new THREE.Group();this.model.name='建筑';this.scene.add(this.model);this.base=box(1000,.08,1000,mat('#e6e2dc'),0,-.3,0);this.base.receiveShadow=true;this.base.castShadow=false;this.scene.add(this.base);
  this.ray=new THREE.Raycaster();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();
  installModelingViewer(this);this.bind();this.loop();
 }
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 setInteractionTool(tool){
  this.interactionTool=tool;
  this.orbit.mouseButtons.LEFT=tool==='pan'?THREE.MOUSE.PAN:THREE.MOUSE.ROTATE;
  this.orbit.touches.ONE=tool==='pan'?THREE.TOUCH.PAN:THREE.TOUCH.ROTATE;
  this.host.dataset.tool=tool;
 }
 bind(){
  const canvas=this.renderer.domElement;let pointer=null;
  canvas.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:0};if(this.walk)canvas.setPointerCapture(e.pointerId);});
  canvas.addEventListener('pointermove',e=>{if(!pointer)return;pointer.moved+=Math.abs(e.clientX-pointer.lastX)+Math.abs(e.clientY-pointer.lastY);if(this.walk){this.yaw-=(e.clientX-pointer.lastX)*.004;this.pitch=clamp(this.pitch-(e.clientY-pointer.lastY)*.003,-1.15,1.15);}pointer.lastX=e.clientX;pointer.lastY=e.clientY;});
  canvas.addEventListener('pointerup',e=>{if(pointer&&pointer.moved<8&&e.button===0&&(this.walk||this.interactionTool!=='pan')){const r=canvas.getBoundingClientRect();this.ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),this.camera);const hits=this.ray.intersectObject(this.model,true).filter(h=>{if(h.object.isLine)return false;if(this.sectionPlane&&this.sectionPlane.distanceToPoint(h.point)<-.001)return false;let o=h.object;while(o){if(!o.visible)return false;o=o.parent;}return true;});let o=hits.map(h=>{let obj=h.object;while(obj&&!obj.userData.entity)obj=obj.parent;return obj;}).find(obj=>obj&&(!this.project||this.walk||!locked(this.project.floors.find(f=>f.id===obj.userData.entity.floorId),obj.userData.entity)));if(o?.userData.entity){const ent=o.userData.entity;if(this.walk&&ent.kind==='opening'&&ent.type==='door'){this.doorStates.set(ent.id,!(this.doorStates.get(ent.id)??true));this.update(this.project,this.options,false);}else if(!this.walk)this.onSelect(ent,e);}}pointer=null;});
  addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea,[contenteditable]'))return;if(this.walk&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight'].includes(e.code)){this.keys.add(e.code);e.preventDefault();}if(this.walk&&e.code==='Escape')this.stopWalk();});
  addEventListener('keyup',e=>this.keys.delete(e.code));addEventListener('blur',()=>this.keys.clear());document.addEventListener('visibilitychange',()=>this.keys.clear());
  canvas.addEventListener('pointerdown',()=>this.host.classList.add('dragging'));
  for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>this.host.classList.remove('dragging'));
  canvas.addEventListener('pointercancel',()=>{pointer=null;});
 }
 clear(){this.model.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.userData.ownMaterial){o.material?.map?.dispose();o.material?.dispose();}});this.model.clear();if(this.selection){this.scene.remove(this.selection);this.selection.geometry.dispose();this.selection.material.dispose();this.selection=null;}}
 update(project,options={},fit=false){
  this.project=project;Object.assign(this.options,options);this.clear();const {floor,exploded,cut,furniture,night}=this.options;
  this.scene.background.set(night?'#222f37':'#f1efeb');this.hemi.intensity=night?.45:1.1;this.sun.intensity=night?.4:2;
  project.floors.forEach((f,index)=>{const g=new THREE.Group();g.name=f.name;g.userData.floorId=f.id;g.position.y=floorElevation(project,index)+(exploded&&!this.walk?index*2.3:0);g.visible=this.walk||floor==='all'||floor===f.id;this.model.add(g);const height=f.height;
   const rooms=f.rooms.length?f.rooms:f.walls.length?[{id:'floor',poly:(()=>{const b=bounds(f);return[[b.x,b.y],[b.x+b.w,b.y],[b.x+b.w,b.y+b.h],[b.x,b.y+b.h]]})(),mat:'tile800',name:'地面'}]:[];
   const below=index>0?project.floors[index-1]:null;
   if(f.cad&&!f.cad.hidden&&this.options.blueprint&&!this.options.includeHidden){const vertices=f.cad.segments.flatMap(s=>[s.a.x,.012,s.a.y,s.b.x,.012,s.b.y]),geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));const reference=new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color:'#87929b',transparent:true,opacity:.45,depthWrite:false}));reference.name='CAD 参考线';reference.userData.ownMaterial=true;g.add(reference);}
   rooms.filter(r=>this.options.includeHidden||!r.hidden).forEach(r=>{const shape=this.shape(r.poly);if(below){for(const st of below.stairs){const poly=this.stairPolygon(st,.06);if(poly.every(p=>pointIn({x:p[0],y:p[1]},r.poly))){const hole=new THREE.Path();poly.forEach((p,i)=>hole[i?'lineTo':'moveTo'](p[0],-p[1]));hole.closePath();shape.holes.push(hole);}}}
    const geo=new THREE.ExtrudeGeometry(shape,{depth:.16,bevelEnabled:false});geo.rotateX(-Math.PI/2);geo.translate(0,-.16,0);const slab=new THREE.Mesh(geo,[floorMat(r.mat||'wood'),mat('#d6d8ce')]);slab.receiveShadow=true;slab.userData.entity={floorId:f.id,kind:'room',id:r.id};g.add(slab);
    if(this.walk){const cs=this.shape(r.poly);for(const st of f.stairs){const poly=this.stairPolygon(st,.06);if(poly.every(p=>pointIn({x:p[0],y:p[1]},r.poly))){const hole=new THREE.Path();poly.forEach((p,i)=>hole[i?'lineTo':'moveTo'](p[0],-p[1]));hole.closePath();cs.holes.push(hole);}}const ceiling=new THREE.Mesh(new THREE.ShapeGeometry(cs),mat('#f7f7f1',{side:THREE.DoubleSide}));ceiling.rotation.x=-Math.PI/2;ceiling.position.y=f.height-.01;ceiling.name='ceiling';g.add(ceiling);}
   });
   if(this.options.blueprint&&f.image&&(this.options.includeHidden||!f.image.hidden)){const i=f.image,tex=new THREE.TextureLoader().load(i.data);tex.colorSpace=THREE.SRGBColorSpace;const mm=new THREE.MeshBasicMaterial({map:tex,transparent:true,opacity:i.opacity,depthWrite:false,side:THREE.DoubleSide}),plane=new THREE.Mesh(new THREE.PlaneGeometry(i.width,i.width*i.pixelHeight/i.pixelWidth),mm);plane.rotation.x=-Math.PI/2;plane.position.set(i.x+i.width/2,.008,i.y+i.width*i.pixelHeight/i.pixelWidth/2);plane.userData.ownMaterial=true;plane.name='底图';g.add(plane);}
   for(const w of f.walls.filter(w=>this.options.includeHidden||!w.hidden)){const wg=new THREE.Group();wg.position.set(w.a.x,0,w.a.y);wg.rotation.y=-Math.atan2(w.b.y-w.a.y,w.b.x-w.a.x);wg.userData.entity={floorId:f.id,kind:'wall',id:w.id};wg.name='墙';const wallHeight=w.height||height;for(const c of wallCells(w,f.openings,wallHeight)){const hi=c.hi;if(hi<=c.lo)continue;const m=box(c.b-c.a,hi-c.lo,w.thickness,mat(w.color||'#edece5'),(c.a+c.b)/2,c.lo);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry),new THREE.LineBasicMaterial({color:'#a4ab9e',transparent:true,opacity:.36}));edges.position.copy(m.position);edges.userData.ownMaterial=true;wg.add(m,edges);}g.add(wg);
    f.openings.filter(o=>o.wallId===w.id&&(this.options.includeHidden||!o.hidden)).forEach(o=>{const og=new THREE.Group();og.position.x=o.offset;og.name=o.type==='door'?'门':'窗';og.userData.entity={floorId:f.id,kind:'opening',id:o.id,type:o.type};const top=Math.min(o.sill+o.height,wallHeight),h=top-o.sill;if(h<=0)return;const m=mat(o.type==='door'?'#a89577':'#63766f');
     [-1,1].forEach(s=>og.add(box(.045,h,w.thickness+.012,m,s*(o.width/2-.023),o.sill,0)));og.add(box(o.width,.045,w.thickness+.012,m,0,top-.045,0));
     if(o.type==='window'){og.add(box(o.width,.04,w.thickness+.02,m,0,o.sill,0));const glass=box(Math.max(.02,o.width-.08),Math.max(.02,h-.07),.025,mat('#c0d6d8',{transparent:true,opacity:.36,roughness:.15,metalness:.1,depthWrite:false}),0,o.sill+.035);og.add(glass);const n=Math.max(1,Math.round(o.width/1.3));for(let k=1;k<n;k++)og.add(box(.035,h,.05,m,-o.width/2+o.width*k/n,o.sill));}
     else{const door=new THREE.Group(),pose=doorPose(o,Math.PI*.42),hinge=pose.hinge;door.position.x=pose.hingeX;const open=this.doorStates.get(o.id)??true;door.rotation.y=open?pose.rotation:0;door.add(box(Math.max(.04,o.width-.065),Math.max(.04,h-.025),.045,mat('#c2ad87'),o.width/2*hinge,0));const knob=box(.12,.025,.075,mat('#77847e',{metalness:.8,roughness:.28}),(o.width-.16)*hinge,Math.min(1,h-.1),.04);door.add(knob);og.add(door);}wg.add(og);
    });
   }
   for(const solid of (f.solids||[]).filter(o=>this.options.includeHidden||!o.hidden)){const mesh=new THREE.Mesh(solidGeometry(solid),mat(solid.color||'#c9bea6'));mesh.userData.entity={floorId:f.id,kind:'solid',id:solid.id};mesh.name=solid.name;mesh.castShadow=true;mesh.receiveShadow=true;const outline=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),new THREE.LineBasicMaterial({color:'#8a8277',transparent:true,opacity:.5}));outline.userData.ownMaterial=true;mesh.add(outline);g.add(mesh);}
   if(furniture)for(const item of f.furniture.filter(o=>this.options.includeHidden||!o.hidden)){const obj=buildFurniture({...item,w:item.w*1000,d:item.d*1000,cx:item.x*1000,cy:item.y*1000});obj.userData.entity={floorId:f.id,kind:'furniture',id:item.id};obj.userData.furnitureSize={w:item.w,d:item.d};if(item.mirrorX)obj.scale.x=-1;obj.name=item.name||item.type;g.add(obj);}
   for(const st of f.stairs.filter(o=>this.options.includeHidden||!o.hidden)){const sg=new THREE.Group();sg.position.set(st.x,0,st.y);sg.rotation.y=-st.rot*Math.PI/180;sg.userData.entity={floorId:f.id,kind:'stair',id:st.id};sg.name='楼梯';const n=Math.ceil(f.height/.18);for(let i=0;i<n;i++){const y=(i+1)*f.height/n;sg.add(box(st.w,.08,st.d/n+.018,mat('#b6a787'),0,y-.08,st.d/2-(i+.5)*st.d/n));}[-1,1].forEach(side=>{for(let i=0;i<=n;i+=2){const y=i*f.height/n;sg.add(box(.025,.9,.025,mat('#63766f'),side*(st.w/2-.04),y,st.d/2-i*st.d/n));}const rail=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,Math.hypot(f.height,st.d),8),mat('#63766f'));const a=new THREE.Vector3(side*(st.w/2-.04),.9,st.d/2),b=new THREE.Vector3(side*(st.w/2-.04),f.height+.9,-st.d/2);rail.position.copy(a).add(b).multiplyScalar(.5);rail.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.sub(a).normalize());sg.add(rail);});g.add(sg);}
  });
  if(this.options.roofVisible!==false&&project.roof!=='none'&&project.floors.at(-1)?.walls.length&&!this.walk){const f=project.floors.at(-1),i=project.floors.length-1,fg=this.model.children[i],b=bounds(f),g=new THREE.Group();g.position.y=f.height+.04;g.name='屋顶';const x=b.x-.3,z=b.y-.3,w=b.w+.6,d=b.h+.6,m=mat('#5a6d64');if(project.roof==='flat')g.add(box(w,.18,d,m,x+w/2,0,z+d/2));else{const h=Math.min(2.8,w*.25);let verts;if(project.roof==='gable'){verts=[[x,0,z],[x+w,0,z],[x+w/2,h,z],[x,0,z+d],[x+w,0,z+d],[x+w/2,h,z+d]];const idx=[0,1,2,3,5,4,0,2,5,0,5,3,2,1,4,2,4,5,0,3,4,0,4,1];const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts.flat(),3));geo.setIndex(idx);geo.computeVertexNormals();g.add(new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:'#607367',side:THREE.DoubleSide,roughness:.9,flatShading:true})));}else{const s=Math.min(w,d)*.3;verts=[[x,0,z],[x+w,0,z],[x+w,0,z+d],[x,0,z+d],[x+w/2,h,z+s],[x+w/2,h,z+d-s]];const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts.flat(),3));geo.setIndex([0,1,4,1,2,5,1,5,4,2,3,5,3,0,4,3,4,5,0,3,2,0,2,1]);geo.computeVertexNormals();g.add(new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:'#607367',side:THREE.DoubleSide,roughness:.9,flatShading:true})));}}g.traverse(o=>o.castShadow=true);fg.add(g);}
  this.setSection(this.options.section,cut);this.markSelection(this.selected);if(fit)this.fit();
 }
 shape(poly){const s=new THREE.Shape();poly.forEach((p,i)=>s[i?'lineTo':'moveTo'](p[0],-p[1]));s.closePath();return s;}
 stairPolygon(st,pad=0){const r=st.rot*Math.PI/180,c=Math.cos(r),s=Math.sin(r);return[[-st.w/2-pad,-st.d/2-pad],[st.w/2+pad,-st.d/2-pad],[st.w/2+pad,st.d/2+pad],[-st.w/2-pad,st.d/2+pad]].map(([x,y])=>[st.x+x*c-y*s,st.y+x*s+y*c]);}
 fit(top=false){if(this.walk)return;this.resize();this.model.updateMatrixWorld(true);const box3=new THREE.Box3();this.model.children.filter(o=>o.visible).forEach(o=>box3.expandByObject(o));if(box3.isEmpty())box3.setFromCenterAndSize(new THREE.Vector3(6,0,5),new THREE.Vector3(12,3,10));const c=box3.getCenter(new THREE.Vector3()),size=box3.getSize(new THREE.Vector3()),vfov=THREE.MathUtils.degToRad(this.camera.fov),hfov=2*Math.atan(Math.tan(vfov/2)*this.camera.aspect),distance=Math.max(size.length()/2,3)/Math.sin(Math.min(vfov,hfov)/2)*1.05;this.orbit.target.copy(c);const direction=top?new THREE.Vector3(0,1,.0001):new THREE.Vector3(.85,1,1.15).normalize();this.camera.position.copy(c).addScaledVector(direction,distance);this.camera.lookAt(c);this.orbit.update();this.sun.target.position.copy(c);this.sun.position.copy(c).add(new THREE.Vector3(-12,22,8));}
 markSelection(sel){
  this.selected=Array.isArray(sel)?sel:sel?[sel]:[];
  if(this.selection){this.scene.remove(this.selection);this.selection.geometry.dispose();this.selection.material.dispose();this.selection=null;}
  if(!this.selected.length||this.walk)return;
  this.model.updateMatrixWorld(true);const bounds=new THREE.Box3();
  this.model.traverse(o=>{const e=o.userData.entity;if(e&&this.selected.some(r=>r.id===e.id&&r.floorId===e.floorId)){let visible=true,p=o;while(p){if(!p.visible)visible=false;p=p.parent;}if(visible)bounds.expandByObject(o);}});
  if(!bounds.isEmpty()){this.selection=new THREE.Box3Helper(bounds,0xd98259);this.scene.add(this.selection);}
 }
 previewFurniture(floorId,item){
  const g=this.model.children.find(g=>g.userData.floorId===floorId),obj=g?.children.find(o=>o.userData.entity?.id===item.id),size=obj?.userData.furnitureSize;
  if(!size)return;obj.position.set(item.x,item.z==null?0:item.z-obj.userData.furnitureBase,item.y);obj.rotation.y=-item.rot*Math.PI/180;obj.scale.set((item.mirrorX?-1:1)*item.w/size.w,1,item.d/size.d);obj.updateMatrixWorld(true);this.markSelection(this.selected);
 }
 replay(){if(this.walk)this.stopWalk();this.animationStart=performance.now();}
 startWalk(floorId,roomId){const f=this.project.floors.find(f=>f.id===floorId)||this.project.floors[0],p=findWalkStart(f,roomId,q=>this.blocked(q,f));if(!p)throw new Error('这个空间暂时没有足够的落脚位置，请选择其他房间或楼层');this.walkFloorId=f.id;if(!this.walk)this.beforeWalk={position:this.camera.position.clone(),target:this.orbit.target.clone()};this.keys.clear();this.walk=true;this.orbit.enabled=false;this.options.exploded=false;this.update(this.project,this.options);this.camera.position.set(p.x,floorElevation(this.project,this.project.floors.indexOf(f))+1.6,p.y);
  let best=-1;this.yaw=0;for(let i=0;i<16;i++){const a=i*Math.PI/8;let free=0;for(let d=.3;d<12;d+=.3){const q={x:p.x-Math.sin(a)*d,y:p.y-Math.cos(a)*d};if(this.blocked(q,f)||(f.rooms.length&&!f.rooms.some(r=>pointIn(q,r.poly))))break;free=d;}if(free>best){best=free;this.yaw=a;}}this.pitch=-.12;this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');this.onStatus(true);
 }
 stopWalk(){if(!this.walk)return;this.walk=false;this.keys.clear();this.orbit.enabled=true;this.update(this.project,this.options);if(this.beforeWalk){this.camera.position.copy(this.beforeWalk.position);this.orbit.target.copy(this.beforeWalk.target);this.camera.lookAt(this.orbit.target);}this.onStatus(false);}
 blocked(p,f){return walkBlocked(p,f,{doorStates:this.doorStates,includeHidden:this.options.includeHidden,furniture:this.options.furniture});}
 step(dt){const forward=(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0)-(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0),side=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0);const f=this.project.floors.find(f=>f.id===this.walkFloorId)||this.project.floors[0];const mag=Math.hypot(forward,side)||1,speed=(this.keys.has('ShiftLeft')?3:1.65)*dt/mag,dx=(-Math.sin(this.yaw)*forward+Math.cos(this.yaw)*side)*speed,dz=(-Math.cos(this.yaw)*forward-Math.sin(this.yaw)*side)*speed,p=this.camera.position;
  if(!this.blocked({x:p.x+dx,y:p.z},f))p.x+=dx;if(!this.blocked({x:p.x,y:p.z+dz},f))p.z+=dz;
  let stairY=null;for(let i=0;i<this.project.floors.length-1;i++){const floor=this.project.floors[i],base=floorElevation(this.project,i);if(Math.abs((p.y-1.6)-(base+floor.height/2))>floor.height/2+.3)continue;for(const st of floor.stairs){const r=-st.rot*Math.PI/180,x=p.x-st.x,y=p.z-st.y,lx=x*Math.cos(r)-y*Math.sin(r),ly=x*Math.sin(r)+y*Math.cos(r);if(Math.abs(lx)<st.w/2-.1&&Math.abs(ly)<st.d/2+.15){stairY=base+clamp((st.d/2-ly)/st.d,0,1)*floor.height;if(stairY>base+floor.height-.2)this.walkFloorId=this.project.floors[i+1].id;else if(stairY<base+.2)this.walkFloorId=floor.id;}}}if(stairY!==null)p.y=stairY+1.6;else{const idx=this.project.floors.findIndex(f=>f.id===this.walkFloorId);p.y=floorElevation(this.project,idx)+1.6;}
  const b=bounds(f);p.x=clamp(p.x,b.x-4,b.x+b.w+4);p.z=clamp(p.z,b.y-4,b.y+b.h+4);this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');
 }
 loop=()=>{this.raf=requestAnimationFrame(this.loop);const now=performance.now(),dt=Math.min((now-this.last)/1000,.05);this.last=now;if(!this.host.clientWidth||!this.host.clientHeight||document.hidden)return;if(this.walk)this.step(dt);else this.orbit.update();if(this.animationStart){const t=clamp((now-this.animationStart)/1800,0,1),ease=1-(1-t)**3;this.model.children.forEach((g,i)=>g.scale.y=Math.max(.001,clamp((ease-i*.09)/(1-i*.09),0,1)));if(t===1)this.animationStart=null;}this.updateModelingHandles?.();this.renderer.render(this.scene,this.camera);};
 screenshot(){const helpers=[this.sectionHelper,this.pullHighlight,this.openingOutline].filter(Boolean),visible=helpers.map(o=>o.visible);helpers.forEach(o=>o.visible=false);this.renderer.render(this.scene,this.camera);this.renderer.domElement.toBlob(b=>download(this.project.name+'-三维.png',b));helpers.forEach((o,i)=>o.visible=visible[i]);}
 async export(format){if(this.walk)this.stopWalk();if(this.animationStart){this.animationStart=null;this.model.children.forEach(g=>g.scale.y=1);}const restore={...this.options};this.update(this.project,{floor:'all',exploded:false,cut:false,furniture:true,blueprint:false,roofVisible:true,includeHidden:true});const exportGroup=this.model.clone(true);exportGroup.children.forEach((g,i)=>{g.visible=true;g.position.y=floorElevation(this.project,i);});const remove=[];exportGroup.traverse(o=>{if(o.isLine||o.name==='底图')remove.push(o);});remove.forEach(o=>o.removeFromParent());exportGroup.updateMatrixWorld(true);
  try{if(format==='glb'){const data=await new GLTFExporter().parseAsync(exportGroup,{binary:true,onlyVisible:true});download(this.project.name+'.glb',new Blob([data],{type:'model/gltf-binary'}));}
  else{const data=new STLExporter().parse(exportGroup,{binary:true});download(this.project.name+'.stl',new Blob([data],{type:'application/octet-stream'}));}}finally{this.update(this.project,restore);}
 }
}
